/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            AI Business Analyst
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description: 
            </h2>
            <h3 className="text-4xl mt-8">(Internship, Duration: 2 months)</h3>
            <h3 className="text-4xl mt-8">Position Overview:</h3>
            <li className="mt-4">
              As an AI Business Analyst Intern, you will play a pivotal role in shaping the future of AI integration in business processes. 
              Your responsibilities will revolve around providing insightful consultations, conducting in-depth research, and preparing 
              comprehensive case studies in any of two key areas:
            <br />
            1. Latest Generative AI (GenAI) Developments: Exploring tools like Claude, Gemini, ChatGPT, and their potential to enhance daily productivity. OR
            <br />
            2. Automation of Standard Operating Procedures: Leveraging Machine Learning and Deep Learning techniques to optimize routine business operations.
            </li>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Conduct market research and analyze trends in Generative AI technologies.</li>
              <li>Develop case studies on the integration of AI tools for enhanced productivity.</li>
              <li>Identify opportunities for automation in business workflows using AI techniques.</li>
              <li>Collaborate with cross-functional teams to brainstorm AI-driven solutions.</li>
              <li>Assist in preparing reports, presentations, and documentation for client consultations.</li>
            </ul>
            <h3 className="text-4xl mt-8">Skills Required:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Basic understanding of AI, Machine Learning, and Deep Learning concepts.</li>
              <li>Strong analytical and research skills.</li>
              <li>Excellent Presentation and documentation skills.</li>
              <li>Proficiency in Project Management tools like Jira, Confluence, or willing to explore them.</li>
              <li>Familiarity with any GenAI tools (e.g., ChatGPT, Claude, Gemini) or willingness to explore them.</li>
              <li>A proactive approach to problem-solving and learning new technologies.  </li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Hands-on experience with cutting-edge AI tools and technologies.</li>
              <li>Mentorship from industry professionals.</li>
              <li>A dynamic and supportive learning environment.</li>
              <li>Certificate of internship and Experience Letter upon completion.</li>
            </ul>
            <h3 className="text-4xl mt-8">How to Apply</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Submit your resume and cover letter to the email address: careers@zenitheum.com OR </li>
              <li>Submit the form on our website: https://zenitheum.com/contactus </li>
            </ul>
            <h3 className="text-4xl mt-8">Application Deadlines</h3>
            <ul className="list-disc list-inside mt-4">
              <li>28th Nov, 2024 </li>
            </ul>
            <br />
            <h3 className="text-4xl mt-8">Even if you do not meet all the requirements, feel free to get in touch with us. We believe in learning as we go. </h3>
            <h3 className="text-4xl mt-8">Join us at Zentiheum and be a part of the AI revolution!</h3>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
