/**
 * This code was generated by Builder.io
 */
import React from "react";

function OurContribution() {
  return (
    <section
      data-layername="ourContribution"
      className="flex flex-wrap gap-10 items-center pr-16 pl-32 mt-32 w-full border-t border-b border-zinc-700 min-h-[913px] max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
        className="flex flex-col grow shrink justify-center self-stretch my-auto text-white min-w-[240px] w-[389px] max-md:max-w-full"
      >
        <h2
          data-layername="ourContribution"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Our Contribution...
        </h2>
        <p
          data-layername="weAreEnthusiasticAboutFiguringOutInnovativeSolutionsToTheProblemsAtHandWeHavePublishedSomeOfTheSolutionsWithSignificantImpactAsResearchPapersThisIsOurWayOfGivingBackToTheCommunity"
          className="mt-10 text-2xl max-md:max-w-full"
        >
          We are enthusiastic about figuring out innovative solutions to the
          problems at hand. We have published some of the solutions with
          significant impact as research papers. This is our way of giving back
          to the community...
          <br />
        </p>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5"
        >
          Access Research Areas
        </button>
      </div>
      <div
        data-layername="divWNode99Feaec272B08085F1A2Bbf1C421530E9671Bbb9"
        className="flex flex-wrap grow shrink justify-center items-center self-stretch my-auto border-l border-zinc-700 min-h-[913px] min-w-[240px] w-[1038px] max-md:max-w-full"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/f33b87bffb14f69435a284aea92d6ac0bb2a9f813736bbbe03dad6169eea167d?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          alt="Research visualization"
          className="object-contain self-stretch my-auto aspect-[1.14] min-w-[240px] rounded-[103px] w-[1037px]"
        />
      </div>
    </section>
  );
}

export default OurContribution;
