/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Header from "./Header";
import OurContribution from "./OurContribution";
import Footer from "./Footer";

function ResearchPage() {
  return (
    <div className="flex overflow-hidden flex-col pb-72 bg-zinc-900 max-md:pb-24">
      <Navbar />
      <Header />
      <OurContribution />
      <Footer />
    </div>
  );
}

export default ResearchPage;
