/**
 * This code was generated by Builder.io
 */
import React from "react";

function Footer() {
  return (
    <footer
      data-layername="footer"
      className="flex flex-col mt-16 w-full min-h-[1199px] max-md:mt-10 max-md:max-w-full"
    >
      <JoinResearchTeam />
      <FooterContent />
      <SocialLinks />
      <FooterRights />
    </footer>
  );
}

function JoinResearchTeam() {
  return (
    <div
      data-layername="divCtaH1stLine"
      className="flex overflow-hidden flex-col justify-center items-center w-full text-white max-w-[1920px] min-h-[598px] max-md:max-w-full"
    >
      <h2
        data-layername="joinOurResearchTeam"
        className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:max-w-full max-md:text-4xl max-md:leading-[50px]"
      >
        Join our Research Team...
      </h2>
      <p
        data-layername="passionateAboutResearchLoveToDiveDeepIntoThisEverExpandingOceanOfAiAndWeb3YouAreMostWelcomeToJoinOurResearchTeamAtZenitheumGetYourHandsDirtyToGetToTheRootsOfTheComplexTechnology"
        className="mt-16 text-2xl text-center w-[986px] max-md:mt-10 max-md:max-w-full"
      >
        Passionate about research? Love to dive deep into this ever expanding
        ocean of AI and web3? You are most welcome to join our research team at
        Zenitheum. Get your hands dirty to get to the roots of the complex
        technology
      </p>
      <button
        data-layername="button"
        className="py-4 pr-8 pl-8 mt-16 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 max-md:mt-10"
      >
        Connect with us
      </button>
    </div>
  );
}

function FooterContent() {
  return (
    <div
      data-layername="footer"
      className="flex overflow-hidden items-start pt-16 pb-7 mt-14 max-w-full w-[1920px] max-md:mt-10"
    >
      <div
        data-layername="divFooterContainer"
        className="flex flex-col items-center h-[427px] w-[1920px] max-md:max-w-full"
      >
        <div
          data-layername="divFooterLinkBlock"
          className="flex flex-wrap py-px w-full border-t border-b border-zinc-700 max-md:max-w-full"
        >
          <CompanyInfo />
          <FooterLinks />
          <ContactInfo />
        </div>
      </div>
    </div>
  );
}

function CompanyInfo() {
  return (
    <div className="flex flex-col px-28 py-5 text-white border-r border-zinc-700 min-w-[240px] w-[649px] max-md:px-5 max-md:max-w-full">
      <div
        data-layername="isolationMode"
        className="flex overflow-hidden gap-2.5 justify-center items-center self-start text-5xl whitespace-nowrap max-md:text-4xl"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/71deb2044f42ad1e40ace9ec8db65ee473e751f901ee4725876460c59b45fc7f?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          alt="Zenitheum logo"
          className="object-contain shrink-0 self-stretch my-auto aspect-[0.98] w-[86px]"
        />
        <div
          data-layername="zenitheum"
          className="self-stretch my-auto max-md:text-4xl"
        >
          Zenitheum
        </div>
      </div>
      <p
        data-layername="zeniteumIsALeadingBlockchainAnalyticsAndAiSolutionsFirmWhereWeStriveToEmpowerBusinessesWithTailoredSolutionsThatDriveGrowthAndEfficiency"
        className="mt-5 text-3xl font-medium tracking-widest"
      >
        Zeniteum is a leading Blockchain Analytics and AI solutions firm, where
        we strive to empower businesses with tailored solutions that drive
        growth and efficiency.
      </p>
    </div>
  );
}

function FooterLinks() {
  const links = [
    "Home",
    "Products",
    "Services",
    "Trainings",
    "Clients",
    "About Us",
    "Research",
    "Careers",
  ];

  return (
    <div
      data-layername="divWNodeEa35C4Ee7A8203Fd1856Fadec6D71926C6D71913"
      className="flex flex-col flex-1 shrink self-start basis-[234px] min-w-[240px] max-md:max-w-full"
    >
      <div
        data-layername="divFooterLinkWrapper"
        className="flex flex-col justify-center px-12 py-6 w-full text-2xl leading-none text-white border-b border-zinc-700 max-md:px-5 max-md:max-w-full"
      >
        <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
          {links.map((link, index) => (
            <div
              key={index}
              data-layername="footerList"
              className="gap-2.5 self-stretch whitespace-nowrap"
            >
              {link}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function ContactInfo() {
  const contactCards = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/755e65f35658c35f0bf56c0a583af86cb82869d550b926f2fe2656002afe4c59?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      title: "Our Head Office",
      content: "Prathamesh Park, \nBaner, Pune, 411045",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/25a98b12ed1fc6ade440b1e04eb0a3ac7519a1436d84e697a85c4901aa383a4f?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      title: "Our Hotline",
      content: "+91 7066497023",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b3c1c7b2ae57386b03f75113996fa66499267a8a78a2bcc1a8f941d195104c29?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      title: "Mail Us",
      content:
        "support@zenitheum.com \ncareers@zenitheum.com \nadmin@zenitheum.com \nrushikesh@zenitheum.com",
    },
  ];

  return (
    <div className="flex flex-wrap items-start w-full max-md:max-w-full">
      {contactCards.map((card, index) => (
        <ContactCard key={index} {...card} />
      ))}
    </div>
  );
}

function ContactCard({ icon, title, content }) {
  return (
    <div
      data-layername="divSCardBlock"
      className="flex flex-col flex-1 shrink self-stretch p-5 border-r basis-0 border-zinc-700 min-w-[240px] max-md:max-w-full"
    >
      <div
        data-layername="divSCardIcon"
        className="flex overflow-hidden justify-center items-center px-5 w-16 h-16 bg-neutral-800 rounded-[32px]"
      >
        <img
          loading="lazy"
          src={icon}
          alt={`${title} icon`}
          className="object-contain self-stretch my-auto w-7 aspect-square"
        />
      </div>
      <div data-layername="divSCardText" className="flex flex-col mt-4 w-full">
        <div
          data-layername={title.toLowerCase().replace(/\s+/g, "")}
          className="text-3xl font-medium leading-none text-zinc-300"
        >
          {title}
        </div>
        <div
          data-layername="pSCardParagraph"
          className="flex-1 shrink pr-5 mt-3.5 w-full text-lg leading-7 text-white whitespace-pre-line"
        >
          {content}
        </div>
      </div>
    </div>
  );
}

function SocialLinks() {
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6f8347fa28e6c597a51142c106a5c91a112ca54bca0519a6156481fba08c0385?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9645fbe951416489c3946599f9a4880e5e04f844b6317c3a9d89b9becf558a41?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      alt: "Twitter",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3223b85f47c7bf2e68fecf03b55564b9a609e051329cf465ab3258847705a83?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      alt: "Instagram",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0b92c1b5d24a4ac2cb2eaf6260a93a8a0fca4d8f0fdc0dbafd494f700b5efbf5?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
      alt: "LinkedIn",
    },
  ];

  return (
    <div
      data-layername="divSocialLinkWrapper"
      className="flex z-10 flex-wrap gap-6 items-start self-end mt-0 mr-28 max-md:mr-2.5"
    >
      {socialIcons.map((icon, index) => (
        <div
          key={index}
          data-layername="link"
          className="flex items-start w-6 max-w-[24px]"
        >
          <div className="flex justify-center items-start w-6 max-w-[24px]">
            <div className="flex overflow-hidden items-start px-0.5 pt-0.5 pb-1 w-6">
              <img
                loading="lazy"
                src={icon.src}
                alt={icon.alt}
                className="object-contain w-5 aspect-square"
              />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function FooterRights() {
  return (
    <div
      data-layername="divFooterRightsWrapper"
      className="flex items-end -mt-6 ml-28 w-full text-base text-white max-md:max-w-full"
    >
      <div data-layername="div" className="min-w-[240px]">
        Copyright © 2024. All rights reserved by Zenitheum
      </div>
    </div>
  );
}

export default Footer;
