/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import JobContent from "./JobContent";

function JobDescription() {
  return (
    <div
      data-layername="jobDescription"
      className="flex overflow-hidden flex-col pb-32 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col mt-0 w-full min-h-[3634px] max-md:max-w-full"
      >
        <JobContent />
      </main>
      <Footer />
    </div>
  );
}

export default JobDescription;
