/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import UpskillWorkforce from "./UpskillWorkforce";
import OfferTraining from "./OfferTraining";
import BookTraining from "./BookTraining";
import Footer from "./Footer";

function CorporateTrainings() {
  return (
    <div className="flex overflow-hidden flex-col pb-40 bg-zinc-900 max-md:pb-24">
      <Header />
      <UpskillWorkforce />
      <OfferTraining />
      <BookTraining />
      <Footer />
    </div>
  );
}

export default CorporateTrainings;
