/**
 * This code was generated by Builder.io
 */
import React from "react";
import TrainImage from "../../images/training2.jpg"

function OfferTraining() {
  return (
    <section
      data-layername="offerTrainingAcross"
      className="flex flex-wrap gap-20 items-center px-12 py-20 w-full text-white border-t border-b border-zinc-700 max-md:pl-5 max-md:mt-10 max-md:max-w-full"
    >
      <img
        loading="lazy"
        src={TrainImage}
        alt="Training programs illustration"
        className="object-cover self-stretch aspect-[1.47] w-[60%] rounded-[100px]  max-md:max-w-full"
      />
      <div
        data-layername="WeOfferContainer"
        className="flex flex-col justify-center self-stretch w-[35%] max-md:max-w-full"
      >
        <h2
          data-layername="WeOfferHeading"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          We offer training programs to clients across...
        </h2>
        <div
          data-layername="Description"
          className="text-2xl max-md:max-w-full"
        >
          Various Sectors: Banking, Healthcare, Education, Marketing and Sales,
          Engineering, Energy, etc
          <br />
          Various levels of management: Senior-level management, Mid-level
          Management, Team Leads, Team Members, etc.
          <br />
          Various skill levels: Familiar/Unfamilier to AI and Blockchain,
          Expert/Beginner, Technical/Non-Technical roles
          <br />
          Various Job Roles: Product Managers, Data Scientists, Data Analysts,
          Web Developers, Software Engineers, DevOps Engineers, Consultants,
          Client Facing Professionals, etc.
          <br />
          Various Departments: Human Resources, Finance, Sales, Marketing,
          Research and Development, IT, etc.
        </div>
      </div>
    </section>
  );
}

export default OfferTraining;
