/**
 * This code was generated by Builder.io
 */
import React from "react";
import TrainImage from "../../images/training2.jpg"

function OfferTraining() {
  return (
    <section
      data-layername="offerTrainingAcross"
      className="flex gap-10 items-center px-11 py-20 text-white border-t border-b border-zinc-700"
    >
      <img
        loading="lazy"
        src={TrainImage}
        alt="Training programs illustration"
        className="object-cover aspect-[1.04] w-[40%] rounded-[100px]"
      />
      <div
        data-layername="WeOfferContainer"
        className="flex flex-col justify-center w-[60%]"
      >
        <h2
          data-layername="WeOfferHeading"
          className="text-6xl font-medium leading-[76px] max-md:text-4xl"
        >
          Our Trainings Span Across...
        </h2>
        <div
          data-layername="Description"
          className="text-2xl mt-12"
        >
          1. Various Sectors: Banking, Healthcare, Education, Marketing and Sales,
          Engineering, Energy, etc
          <br />
          2. Various levels of management: Senior/Mid-level
          Management, TLs and Team Members, etc.
          <br />
          3. Various skill levels: Familiar/Unfamilier to AI and Blockchain,
          Expert/Beginner, Tech/Non-Tech roles
          <br />
          4. Various Departments: Human Resources, Finance, Sales, Marketing,
          R&D, IT, etc.
          <br />
          5. Various Job Roles: Product Managers, Data Scientists, Data Analysts,
          Web Developers, Software Engineers, DevOps Engineers, Consultants,
          Client Facing Professionals, etc.
        </div>
      </div>
    </section>
  );
}

export default OfferTraining;
