/**
 * This code was generated by Builder.io
 */
import React from "react";
import UpskillImage from "../../images/training1.jpg"

function UpskillWorkforce() {
  return (
    <section
      data-layername="TextImageContainer"
      className="flex flex-wrap gap-10 items-center px-20 py-20 w-full text-white border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="UpskillContainer"
        className="flex flex-col grow shrink justify-center self-stretch w-[25%] max-md:max-w-full"
      >
        <h2
          data-layername="UpskillHeader"
          className="self-start text-6xl font-medium text-center leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Upskill your workforce
        </h2>
        <div
          data-layername="Description"
          className="mt-7 text-2xl max-md:max-w-full"
        >
          <br />
          <span className="text-4xl">
            Book our Employee Training Session with hands-on experience about:
          </span>
          <br />
          <br />
          <ul>
            <li>
              Latest GenAI developments like Claude, Gemini, ChatGPT and their
              integration into your daily life for enhanced productivity.
            </li>
          </ul>
          <ul>
            <li>
              Use of Machine Learning and Deep Learning techniques to automate
              Standard operating procedures.
            </li>
          </ul>
          <br />
          <ul>
            <li>
              Latest Web3 developments with familarity to its concepts, its
              application in various domains and its scope into your work.
            </li>
          </ul>
          <br />
        </div>
      </div>
      <img
        loading="lazy"
        src={UpskillImage}
        alt="Upskill your workforce illustration"
        className="object-cover grow shrink self-stretch w-[55%] aspect-[1.47] rounded-[100px] max-md:max-w-full"
      />
    </section>
  );
}

export default UpskillWorkforce;
