/**
 * This code was generated by Builder.io
 */
import React from "react";

const ClientsImage = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d221cc86a702252a33e10534568191d3039ac355cd5c9860c876d763f9f8c930?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
      alt="Our clients showcase"
      className="object-contain mt-32 w-full aspect-[1.81] max-md:mt-10 max-md:mr-2.5 max-md:max-w-full"
    />
  );
};

export default ClientsImage;
