/**
 * This code was generated by Builder.io
 */
import React from "react";
import Layout from "../Layout/Layout";
import Header from "./Header";
import Projects from "./Projects";
import ClientsImage from "./ClientsImage";
import CallToAction from "./CallToAction";

const HomePage = () => {
  return (
    <Layout>
      <Header />
      <Projects />
      <ClientsImage />
      <CallToAction />
    </Layout>
  );
};

export default HomePage;
