/**
 * This code was generated by Builder.io
 */
import React from "react";
import BlockchainAnalyticsServices from "./components/BlockchainAnalyticsServices";

function App() {
  return (
    <div className="App">
      <BlockchainAnalyticsServices />
    </div>
  );
}

export default App;
