/**
 * This code was generated by Builder.io
 */
import React from "react";

const NavTab = ({ children, isActive }) => (
  <div
    className={`overflow-hidden flex-1 shrink gap-2.5 self-stretch py-10 px-12 border-r border-b ${
      isActive
        ? "text-blue-700 bg-white border-zinc-900"
        : "bg-zinc-900 border-zinc-700"
    } min-h-[100px] max-md:px-5`}
  >
    {children}
  </div>
);

const Navbar = () => {
  const tabs = [
    { label: "home", isActive: false },
    { label: "Products", isActive: false },
    { label: "services", isActive: true },
    { label: "trainings", isActive: false },
    { label: "our clients", isActive: false },
    { label: "about us", isActive: false },
    { label: "research", isActive: false },
    { label: "Careers", isActive: false },
  ];

  return (
    <nav
      data-layername="navbar"
      className="flex flex-wrap items-start w-full border-b border-zinc-700 max-md:max-w-full"
    >
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase whitespace-nowrap basis-[140px] min-w-[240px] max-md:max-w-full">
        {tabs.slice(0, 4).map((tab, index) => (
          <NavTab key={index} isActive={tab.isActive}>
            {tab.label}
          </NavTab>
        ))}
      </div>
      <div
        data-layername="logoFrame"
        className="flex overflow-hidden flex-col px-16 border border-solid bg-zinc-900 border-neutral-700 min-h-[100px] min-w-[240px] w-[245px] max-md:px-5"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c1eb17052800bf7be78ee46d52fbd3fd696e928834eda3f8990dd805c0e7ab4?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          alt="Company logo"
          className="object-contain aspect-[1.04] w-[99px]"
        />
      </div>
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase basis-[140px] min-w-[240px] max-md:max-w-full">
        {tabs.slice(4).map((tab, index) => (
          <NavTab key={index + 4} isActive={tab.isActive}>
            {tab.label}
          </NavTab>
        ))}
      </div>
    </nav>
  );
};

export default Navbar;
