/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Backend Developer
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description: 
            </h2>
            <h3 className="text-4xl mt-8">(Internship, Duration: 2 months)</h3>
            <h3 className="text-4xl mt-8">Position Overview</h3>
            <li className="mt-4">
            We are seeking a skilled Backend Developer to join our innovative team at Zentiheum. Our focus is on developing an algorithmic trading bot for blockchain price prediction. 
            <br />
            As a backend developer, you will design and manage robust infrastructure, ensuring seamless data flow and system reliability. 
            You will play a pivotal role in building scalable APIs and integrating blockchain technologies to support our advanced prediction algorithms.
            </li>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Backend Infrastructure Development: Design, implement, and maintain the core infrastructure supporting our trading bot, ensuring scalability and high availability.</li>
              <li>API Management: Develop, integrate, and manage APIs for data retrieval, trading platform interaction, and blockchain connectivity.</li>
              <li>Data Handling: Implement efficient data pipelines for real-time data processing and storage.</li>
              <li>System Monitoring & Optimization: Monitor backend performance and optimize systems for speed and reliability.</li>
              <li>Familarity with react.js/node.js and Tailwind CSS</li>
              <li>Smart Contract Interaction: Interact with blockchain-based smart contracts using Vyper/ Web3.py, ensuring secure and efficient data transactions.</li>
            </ul>
            <h3 className="text-4xl mt-8">Skills Required:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Strong proficiency in backend programming languages (e.g., Python, Node.js, or Go).</li>
              <li>Hands-on experience with RESTful and WebSocket APIs, and familiarity with blockchain APIs is a plus.</li>
              <li>Deep understanding of database management systems (SQL and NoSQL).</li>
              <li>Knowledge of algorithmic trading systems or blockchain-based applications is desirable.</li>
              <li>Prior experience in Web3, blockchain, or related fields is a plus. </li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Opportunity to work at the intersection of cutting-edge technologies: AI, blockchain, and algorithmic trading.</li>
              <li>Mentorship from industry professionals.</li>
              <li>Growth opportunities in a fast-paced, innovative startup environment.</li>
              <li>Certificate of internship and Experience Letter upon completion.</li>
            </ul>
            <h3 className="text-4xl mt-8">How to Apply</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Submit your resume and cover letter to the email address: careers@zenitheum.com OR </li>
              <li>Submit the form on our website: https://zenitheum.com/contactus </li>
            </ul>
            <h3 className="text-4xl mt-8">Application Deadlines</h3>
            <ul className="list-disc list-inside mt-4">
              <li>28th Nov, 2024 </li>
            </ul>
            <br />
            <h3 className="text-4xl mt-8">Even if you do not meet all the requirements, feel free to get in touch with us. We believe in learning as we go. </h3>
            <h3 className="text-4xl mt-8">Join us at Zentiheum and be a part of the AI revolution!</h3>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
