/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center px-28 py-24 w-full min-h-[553px] max-md:px-5 max-md:py-24 max-md:max-w-full"
      >
        <div
          data-layername="divCtaH1stLine"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="corporateTrainings"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            Corporate Trainings
          </h1>
          <p
            data-layername="ourJourneyBlockchainIsRisingAndSoIsOurServiceOurJourneyInTheBlockchainAndAiIndustryHasBeenPropelledByAPassionForExcellenceAndADedicationToProvidingImpactfulSolutions"
            className="mt-16 text-2xl border border-black border-solid w-[986px] max-md:mt-10 max-md:max-w-full"
          >
            Our Corporate Trainings are designed to equip businesses with the
            latest skills and knowledge essential for thriving in the fast-paced
            world of blockchain and AI. We offer comprehensive programs with
            hands-on experience that cater to various topics and skill levels,
            ensuring that every participant can enhance their expertise and
            confidence.
            <br />
            We have custom-tailored training programs for all types of
            individuals in your company.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
