/**
 * This code was generated by Builder.io
 */
import React from "react";

function OfferTraining() {
  return (
    <section
      data-layername="offerTrainingAcross"
      className="flex flex-wrap gap-10 items-center pl-14 mt-32 w-full text-white border-t border-b border-zinc-700 max-md:pl-5 max-md:mt-10 max-md:max-w-full"
    >
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/555514829f9650a07660b19ffa71acf32e801afabbf1d1de3bcba1fe8743ba74?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
        alt="Training programs illustration"
        className="object-contain self-stretch my-auto aspect-[1.51] min-w-[240px] rounded-[100px] w-[1136px] max-md:max-w-full"
      />
      <div
        data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
        className="flex flex-col justify-center self-stretch my-auto min-h-[828px] min-w-[240px] w-[602px] max-md:max-w-full"
      >
        <h2
          data-layername="weOfferTrainingProgramsToClientsAcross"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          We offer training programs to clients across...
        </h2>
        <div
          data-layername="variousSectorsBankingHealthcareEducationMarketingAndSalesEngineeringEnergyEtcVariousLevelsOfManagementSeniorLevelManagementMidLevelManagementTeamLeadsTeamMembersEtcVariousSkillLevelsFamiliarUnfamilierToAiAndBlockchainExpertBeginnerTechnicalNonTechnicalRolesVariousJobRolesProductManagersDataScientistsDataAnalystsWebDevelopersSoftwareEngineersDevOpsEngineersConsultantsClientFacingProfessionalsEtcVariousDepartmentsHumanResourcesFinanceSalesMarketingResearchAndDevelopmentItEtc"
          className="text-2xl max-md:max-w-full"
        >
          Various Sectors: Banking, Healthcare, Education, Marketing and Sales,
          Engineering, Energy, etc
          <br />
          Various levels of management: Senior-level management, Mid-level
          Management, Team Leads, Team Members, etc.
          <br />
          Various skill levels: Familiar/Unfamilier to AI and Blockchain,
          Expert/Beginner, Technical/Non-Technical roles
          <br />
          Various Job Roles: Product Managers, Data Scientists, Data Analysts,
          Web Developers, Software Engineers, DevOps Engineers, Consultants,
          Client Facing Professionals, etc.
          <br />
          Various Departments: Human Resources, Finance, Sales, Marketing,
          Research and Development, IT, etc.
        </div>
      </div>
    </section>
  );
}

export default OfferTraining;
