/**
 * This code was generated by Builder.io
 */
import React from "react";
import Layout from "../components/Layout/Layout";
import Header from "../components/Header/Header";
import Founder from "../components/Founder/Founder";
import Team from "../components/Team/Team";
import CoreValues from "../components/CoreValues/CoreValues";

const AboutUs = () => {
  return (
    <Layout>
      <Header />
      <Founder />
      <Team />
      <CoreValues />
    </Layout>
  );
};

export default AboutUs;
