/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-w-[1920px] max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center py-24 pr-28 pl-28 w-full min-h-[553px] max-md:px-5 max-md:py-24"
      >
        <div
          data-layername="divCtaH1stLine"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="products"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            Products
          </h1>
          <p
            data-layername="discoverTheTangibleImpactOfOurExpertiseInBlockchainDataEngineeringAndAiThroughOurShowcaseOfRemarkableProjectsFromCuttingEdgeSolutionsForBusinessesToInnovativeApplicationsThatDriveSocialChangeEachProjectEmbodiesOurCommitmentToExcellenceAndInnovationExploreTheSuccessStoriesAndWitnessHowOurTransformativeTechnologiesAreShapingIndustriesAndEmpoweringOurClientsToThriveInAnInterconnectedWorld"
            className="mt-16 text-2xl w-[986px] max-md:mt-10 max-md:max-w-full"
          >
            Discover the tangible impact of our expertise in Blockchain, Data
            Engineering, and AI through our showcase of remarkable projects.
            From cutting-edge solutions for businesses to innovative
            applications that drive social change, each project embodies our
            commitment to excellence and innovation. Explore the success stories
            and witness how our transformative technologies are shaping
            industries and empowering our clients to thrive in an interconnected
            world.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
