/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "../Layout/Navbar";
import Header from "../Header/Header";
import ProductSection from "./ProductSection";
import Footer from "../Footer/Footer";

const products = [
  {
    title: "Algorithmic Trading Bot",
    description:
      "This leading-edge product represents the fusion of AI and blockchain technology, providing real-time price prediction for BTC and ETH. The bot supports API integration and can be accessed through python.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/88c826c266303ab474d97a68040c341d8427d6916225c885663ec0af8828e88b?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    imageAlt: "Algorithmic Trading Bot visualization",
    isReversed: false,
  },
  {
    title: "Portfolio Management Toolkit",
    description:
      "Offering a tailored Crypto Portfolio Management Guide, Zenitheum empowers personal investors to navigate the complexities of the cryptocurrency market. With a focus on maximizing returns while minimizing risks, our guide is the best starting point for your analysis. If you have any further queries/ need more clarity/ periodic revamping of the portfolio, we deliver free after-sales services that enable clients to make informed investment decisions with greater confidence, ensuring their portfolios are well-balanced and aligned with market trends. Let us guide you through the ever-evolving landscape of crypto investments, providing the support and expertise necessary to thrive in this digital era.",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/2d8cfd94f0b75aca2260faedeaa997bd7163197800a88e82e0249f5872ceb1f5?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    imageAlt: "Portfolio Management Toolkit interface",
    isReversed: true,
  },
];

function ProductsPage() {
  return (
    <div
      data-layername="products"
      className="flex overflow-hidden flex-col pb-64 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col w-full min-h-[4374px] max-md:max-w-full"
      >
        <Header />
        {products.map((product, index) => (
          <ProductSection key={index} {...product} />
        ))}
      </main>
      <Footer />
    </div>
  );
}

export default ProductsPage;
