/**
 * This code was generated by Rushikesh
 */
import React from "react";

function ProductSection({
  title,
  description,
  imageSrc,
  imageAlt,
  isReversed,
}) {
  const containerClasses = `flex gap-10 px-10 py-20 justify-center items-center text-white border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10 ${
    isReversed ? "flex-row-reverse" : ""
  }`;

  return (
    <section className={containerClasses}>
      <div
        data-layername="TitleContainer"
        className="flex flex-col grow shrink justify-center w-[50%]"
      >
        <h2 className="text-6xl font-medium leading-[76px] max-md:text-4xl max-md:leading-[52px]">
          {title}
        </h2>
        <p className="mt-10 text-2xl ">{description}</p>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-cover grow shrink aspect-[1.2] rounded-[100px] w-[45%]"
      />
    </section>
  );
}

export default ProductSection;
