/**
 * This code was generated by Rushikesh
 */
import React from "react";

function ProductSection({
  title,
  description,
  imageSrc,
  imageAlt,
  isReversed,
}) {
  const containerClasses = `flex flex-wrap gap-20 px-20 py-20 justify-center items-center max-w-full text-white border-t border-b border-zinc-700 w-[1920px] max-md:px-5 max-md:mt-10 ${
    isReversed ? "flex-row-reverse" : ""
  }`;

  return (
    <section className={containerClasses}>
      <div
        data-layername="TitleContainer"
        className="flex flex-col grow shrink justify-center self-stretch w-[25%] max-md:max-w-full"
      >
        <h2 className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]">
          {title}
        </h2>
        <p className="mt-10 text-2xl max-md:max-w-full">{description}</p>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-cover grow shrink self-stretch aspect-[1.47] rounded-[100px] w-[55%] max-md:max-w-full"
      />
    </section>
  );
}

export default ProductSection;
