/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import ProductSection from "./ProductSection";
import Footer from "./Footer";
import AlgoBot from "../../images/algo_trading.png";
import PortImage from "../../images/crypto_portfolio.png";
import CallToAction from "./CallToAction";

const products = [
  {
    title: "Algorithmic Trading Bot",
    description:
      "This leading-edge product represents the fusion of AI and blockchain technology, providing real-time price prediction for BTC and ETH. The bot supports API integration and can be accessed through python.",
    imageSrc:AlgoBot,
    imageAlt: "Algorithmic Trading Bot visualization",
    isReversed: false,
  },
  {
    title: "Portfolio Management Toolkit",
    description: 
      "Offering a tailored Crypto Portfolio Management Guide, Zenitheum empowers personal investors to navigate the complexities of the cryptocurrency market. With a focus on maximizing returns while minimizing risks, our guide is the best starting point for your analysis. If you have any further queries/ need more clarity/ periodic revamping of the portfolio, we deliver free after-sales services that enable clients to make informed investment decisions with greater confidence, ensuring their portfolios are well-balanced and aligned with market trends. Let us guide you through the ever-evolving landscape of crypto investments, providing the support and expertise necessary to thrive in this digital era.",
    imageSrc: PortImage,
    imageAlt: "Portfolio Management Toolkit interface",
    isReversed: true,
  },
];

function ProductsPage() {
  return (
    <div
      data-layername="products"
      className="flex overflow-hidden flex-col pb-40 bg-zinc-900 max-md:pb-24"
    >
      <main
        data-layername="main"
        className="flex flex-col w-full max-md:max-w-full"
      >
        <Header />
        {products.map((product, index) => (
          <ProductSection key={index} {...product} />
        ))}
      <CallToAction />
      <Footer />
      </main>
    </div>
  );
}

export default ProductsPage;
