/**
 * This code was generated by Builder.io
 */
import React from "react";
import NavTab from "./NavTab";

const navItems = [
  { label: "home", isActive: false },
  { label: "products", isActive: true },
  { label: "services", isActive: false },
  { label: "trainings", isActive: false },
  { label: "our clients", isActive: false },
  { label: "about us", isActive: false },
  { label: "research", isActive: false },
  { label: "Careers", isActive: false },
];

function Navbar() {
  return (
    <nav
      data-layername="navbar"
      className="flex flex-wrap items-start w-full border-b border-zinc-700 max-md:max-w-full"
    >
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase whitespace-nowrap basis-[140px] min-w-[240px] max-md:max-w-full">
        {navItems.slice(0, 4).map((item, index) => (
          <NavTab key={index} label={item.label} isActive={item.isActive} />
        ))}
      </div>
      <div
        data-layername="logoFrame"
        className="flex overflow-hidden flex-col px-16 border border-solid bg-zinc-900 border-neutral-700 min-h-[100px] min-w-[240px] w-[245px] max-md:px-5"
      >
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c1eb17052800bf7be78ee46d52fbd3fd696e928834eda3f8990dd805c0e7ab4?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          alt="Company logo"
          className="object-contain aspect-[1.04] w-[99px]"
        />
      </div>
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase basis-[140px] min-w-[240px] max-md:max-w-full">
        {navItems.slice(4).map((item, index) => (
          <NavTab key={index + 4} label={item.label} isActive={item.isActive} />
        ))}
      </div>
    </nav>
  );
}

export default Navbar;
