/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import ServiceSection from "./ServiceSection";
import CTASection from "./CTASection";
import Footer from "./Footer";
import GenAI from "../../images/genai.png";
import BussImage from "../../images/data_analytics.png";
import AIImage from "../../images/ML2.png";
import { useEffect } from "react";

function AIServices() {
  useEffect(() => {
    window.scrollTo(0,0);
  })
  const services = [
    {
      title: "GenAI Innovations",
      description:
        "With the buzz around GenAI language models like Gemini, Claude and ChatGPT, our team holds speciality in integrating these into your business cases as well as designing novel GenAI models. We hold expertise in all genres of GenAI innovations, whether Images, Text, or Speech.",
      imageSrc:GenAI,
      imageAlt: "GenAI Innovations visual representation",
      buttonText: "Explore the scope",
      imageFirst: false,
    },
    {
      title: "Business Data Analytics",
      description:
        "Our Business Data Analytics services empower organizations to transform complex data into meaningful strategies... Along with the complex analysis, we also hold expertise in Data Visualization using Tableau and PowerBI",
      imageSrc: BussImage,
      imageAlt: "Business Data Analytics visual representation",
      buttonText: "Explore the scope",
      imageFirst: true,
    },
    {
      title: "AI-ML Modelling",
      description:
        "Our dedicated Model Development and Deployment services ensure seamless integration of AI into existing infrastructures. Experience how our AI solutions can significantly transform your business landscape.",
      imageSrc:AIImage,
      imageAlt: "AI-ML Modelling visual representation",
      buttonText: "Explore the scope",
      imageFirst: false,
    },
  ];

  return (
    <div className="flex overflow-hidden pb-40 flex-col bg-zinc-900">
      <main className="flex flex-col w-full max-md:max-w-full">
        <Header />
        {services.map((service, index) => (
          <ServiceSection key={index} {...service} />
        ))}
        <CTASection />
        <Footer />
      </main>
    </div>
  );
}

export default AIServices;
