/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center w-[75%] py-20 max-md:px-5 max-md:py-24"
      >
        <div
          data-layername="divCtaH1stLine"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="aiServicesHeader"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            AI Services
          </h1>
          <p
            data-layername="Description"
            className="mt-16 text-2xl w-[986px] max-md:mt-10 max-md:max-w-full"
          >
            We delve into the intricacies of devising advanced Machine Learning
            and Deep Learning algorithms tailored for various business
            applications. Our offerings are designed to enhance operational
            efficiency and provide actionable insights, propelling companies
            towards their strategic objectives.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
