/**
 * This code was generated by Rushikesh
 */
import React from "react";
import { useNavigate } from "react-router-dom";

function ServiceSection({
  title,
  description,
  imageSrc,
  imageAlt,
  buttonText,
  imageFirst,
}) {
  const navigate = useNavigate();

  const handleViewServices = () => {
    navigate('/contactus'); 
  };

  const contentSection = (
    <div
      data-layername="ContentContainer"
      className="flex flex-col grow shrink justify-center self-stretch w-[25%] max-md:max-w-full"
    >
      <h2
        data-layername={title.toLowerCase().replace(/\s+/g, "-")}
        className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
      >
        {title}
      </h2>
      <p
        data-layername={description.toLowerCase().replace(/\s+/g, "-")}
        className="mt-10 text-2xl max-md:max-w-full"
      >
        {description}
      </p>
      <button
          data-layername="button"
          className="justify-center text-center py-4 w-fit pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label={buttonText}
        >
          {buttonText}
        </button>
    </div>
  );

  const imageSection = (
    <img
      loading="lazy"
      src={imageSrc}
      alt={imageAlt}
      className="object-cover grow shrink self-stretch aspect-[1.47] w-[45%] rounded-[101px] max-md:max-w-full"
    />
  );

  return (
    <section
      data-layername={title.toLowerCase().replace(/\s+/g, "-")}
      className="flex flex-wrap items-center px-16 py-24 gap-10 w-full text-white border-t border-b border-zinc-700 max-md:px-5"
    >
      {imageFirst ? (
        <>
          {imageSection}
          {contentSection}
        </>
      ) : (
        <>
          {contentSection}
          {imageSection}
        </>
      )}
    </section>
  );
}

export default ServiceSection;
