/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "../Navbar/Navbar";
import Footer from "../Footer/Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col pb-40 bg-zinc-900 max-md:pb-24">
      <Navbar />
      <main className="flex flex-col w-full min-h-[3875px] max-md:max-w-full">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
