/**
 * This code was generated by Builder.io
 */
import React from "react";

const Header = () => {
  return (
    <header className="flex flex-col items-center w-full text-center text-white max-md:max-w-full">
      <div className="flex overflow-hidden justify-center items-center px-28 py-32 w-full min-h-[553px] max-md:px-5 max-md:py-24 max-md:max-w-full">
        <div className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
          <h1 className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl">
            Our Clients
          </h1>
          <p className="mt-16 text-2xl border border-black border-solid w-[986px] max-md:mt-10 max-md:max-w-full">
            We are dedicated to fostering long-term relationships that empower
            our clients to achieve their goals in this rapidly evolving digital
            landscape. We have delivered satisfactory services to our clients
            all across the globe including, Singapore, USA, Italy and India.
          </p>
        </div>
      </div>
    </header>
  );
};

export default Header;
