/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Header from "./Header";
import JobListings from "./JobListings";
import LifeAtZenitheum from "./LifeAtZenitheum";
import Footer from "./Footer";

function Careers() {
  return (
    <div
      data-layername="careers"
      className="flex overflow-hidden flex-col pb-48 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <Header />
      <JobListings />
      <LifeAtZenitheum />
      <Footer />
    </div>
  );
}

export default Careers;
