/**
 * This code was generated by Builder.io
 */
import React from "react";
import FooterLinks from "./FooterLinks";
import ContactInfo from "./ContactInfo";
import SocialLinks from "./SocialLinks";

function Footer() {
  return (
    <footer
      data-layername="footer"
      className="flex overflow-hidden items-start pt-16 pb-7 mt-32 max-w-full w-[1920px] max-md:mt-10"
    >
      <div
        data-layername="divFooterContainer"
        className="flex flex-col h-[427px] min-w-[240px] w-[1920px] max-md:max-w-full"
      >
        <div
          data-layername="divFooterLinkBlock"
          className="flex flex-wrap self-center py-px w-full border-t border-b border-zinc-700"
        >
          <div className="flex flex-col px-28 py-5 text-white border-r border-zinc-700 min-w-[240px] w-[649px] max-md:px-5 max-md:max-w-full">
            <div
              data-layername="isolationMode"
              className="flex overflow-hidden gap-2.5 justify-center items-center self-start text-5xl whitespace-nowrap max-md:text-4xl"
            >
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/71deb2044f42ad1e40ace9ec8db65ee473e751f901ee4725876460c59b45fc7f?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                alt="Zenitheum logo"
                className="object-contain shrink-0 self-stretch my-auto aspect-[0.98] w-[86px]"
              />
              <div
                data-layername="zenitheum"
                className="self-stretch my-auto max-md:text-4xl"
              >
                Zenitheum
              </div>
            </div>
            Continuing from where we left off:
            <p
              data-layername="zeniteumIsALeadingBlockchainAnalyticsAndAiSolutionsFirmWhereWeStriveToEmpowerBusinessesWithTailoredSolutionsThatDriveGrowthAndEfficiency"
              className="mt-5 text-3xl font-medium tracking-widest"
            >
              Zeniteum is a leading Blockchain Analytics and AI solutions firm,
              where we strive to empower businesses with tailored solutions that
              drive growth and efficiency.
            </p>
          </div>
          <FooterLinks />
          <ContactInfo />
        </div>
        <div
          data-layername="divFppterRightsBox"
          className="flex flex-wrap flex-1 gap-5 justify-center items-end px-28 mt-2.5 size-full max-md:px-5 max-md:max-w-full"
        >
          <div
            data-layername="divFooterRightsWrapper"
            className="flex flex-1 shrink items-end text-base text-white basis-0 min-w-[240px] max-md:max-w-full"
          >
            <div data-layername="div" className="min-w-[240px]">
              Copyright © 2024. All rights reserved by Zenitheum
            </div>
          </div>
          <SocialLinks />
        </div>
      </div>
    </footer>
  );
}

export default Footer;
