/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-w-[1920px] max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center px-28 py-20 w-full min-h-[553px] max-md:px-5"
      >
        <div
          data-layername="divCtaH1stLine"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="careers"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            Careers
          </h1>
          <p
            data-layername="welcomeToZenitheumReadyToEmbarkOnAnExcitingCareerJourneyFilledWithInnovationAndGrowthAtZenitheumWeOfferAVibrantAndInclusiveWorkEnvironmentThatFostersCreativityAndCollaborationJoinOurTeamOfTalentedProfessionalsFromDiverseBackgroundsAndExploreEndlessOpportunitiesInBlockchainDataScienceAndAiWhetherYoureAnExperiencedExpertAFreshGraduateOrACollegeStudentWeWelcomeAllPassionateIndividualsEagerToMakeADifferenceInTheWorldOfTechnologyDiscoverARewardingCareerPathWithUsAndBePartOfShapingABrighterFutureForTheGlobalCommunity"
            className="mt-16 text-2xl w-[986px] max-md:mt-10 max-md:max-w-full"
          >
            Welcome to Zenitheum. Ready to embark on an exciting career journey
            filled with innovation and growth? At Zenitheum, we offer a vibrant
            and inclusive work environment that fosters creativity and
            collaboration. Join our team of talented professionals from diverse
            backgrounds and explore endless opportunities in Blockchain, Data
            Science, and AI. Whether you're an experienced expert, a fresh
            graduate or a college student, we welcome all passionate individuals
            eager to make a difference in the world of technology. Discover a
            rewarding career path with us and be part of shaping a brighter
            future for the global community.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
