/**
 * This code was generated by Builder.io
 */
import React from "react";
import JobCard from "./JobCard";

const jobListings = [
  { title: "Full-Stack Developer", type: "Full-Time", location: "Remote" },
  { title: "Data Scientist", type: "Full-Time", location: "Remote" },
  { title: "Web3/AI Consultant", type: "Internship", location: "Remote" },
  { title: "QA Engineer", type: "Full-Time", location: "Remote" },
  { title: "Product Manager", type: "Internship", location: "Remote" },
];

function JobListings() {
  return (
    <section
      data-layername="weAreHiring"
      className="flex flex-wrap gap-10 items-center pl-32 mt-32 w-full border-t border-b border-zinc-700 max-w-[1920px] max-md:pl-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
        className="flex flex-col grow shrink justify-center self-stretch my-auto text-white min-w-[240px] w-[389px] max-md:max-w-full"
      >
        <h2
          data-layername="weAreHiring"
          className="text-6xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
        >
          We are hiring
        </h2>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5"
        >
          APPLY NOW
        </button>
      </div>
      <div
        data-layername="divWNode99Feaec272B08085F1A2Bbf1C421530E9671Bbb9"
        className="flex flex-wrap grow shrink justify-center items-center self-stretch my-auto border-l border-zinc-700 min-w-[240px] w-[1106px] max-md:max-w-full"
      >
        {jobListings.map((job, index) => (
          <JobCard
            key={index}
            title={job.title}
            type={job.type}
            location={job.location}
          />
        ))}
      </div>
    </section>
  );
}

export default JobListings;
