/**
 * This code was generated by Rushikesh
 */
import React from "react";
import JobCard from "./JobCard";
import { useNavigate } from "react-router-dom";

const jobListings = [
  { title: "Backend Developer", type: "Internship", location: "Remote",buttonlinkpage : "/careers/joblistings-backend" },
  { title: "Data Scientist", type: "Internship", location: "Remote",buttonlinkpage : "/careers/joblistings-datascientist" },
  { title: "AI Business Analyst", type: "Internship", location: "Remote",buttonlinkpage :"/careers/joblistings-aibusinessanalyst" },
  { title: "Web3 Business Analyst", type: "Internship", location: "Remote",buttonlinkpage : "/careers/joblistings-web3businessanalyst" },
  { title: "Web3 Data Analyst", type: "Internship", location: "Remote",buttonlinkpage : "/careers/joblistings-solditydeveloper" },
];

function JobListings() {
  const navigate = useNavigate();

  const handleViewServices = () => {
    navigate("/contactus");
  };
  return (
    <section
      data-layername="Container"
      className="flex gap-5 items-center pl-32 w-full border-t border-b border-zinc-700  max-md:pl-5 max-md:mt-10"
    >
      <div
        data-layername="HiringBlock"
        className="flex flex-col grow shrink justify-center w-[25%] my-auto text-white  max-md:max-w-full"
      >
        <h2
          data-layername="weAreHiring"
          className="text-6xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
        >
          We are hiring
        </h2>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label="Apply Now"
        >
          Apply Now
        </button>
      </div>
      <div
        data-layername="JobPostsContainer"
        className="flex flex-wrap grow shrink justify-center items-center w-[75%] border-l border-zinc-700 "
      >
        {jobListings.map((job, index) => (
          <JobCard
            key={index}
            title={job.title}
            type={job.type}
            location={job.location}
            buttonlinkpage={job.buttonlinkpage}
          />
        ))}
      </div>
    </section>
  );
}

export default JobListings;
