/**
 * This code was generated by Builder.io
 */
import React from "react";

function LifeAtZenitheum() {
  return (
    <section
      data-layername="lifeAtZenitheum"
      className="flex flex-wrap gap-10 items-center pl-32 mt-32 w-full text-white border-t border-b border-zinc-700 max-w-[1920px] max-md:pl-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="lifeAtZ"
        className="flex flex-col grow shrink justify-center self-stretch my-auto min-w-[240px] w-[389px] max-md:max-w-full"
      >
        <h2
          data-layername="lifeAtZenitheum"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Life at Zenitheum
        </h2>
        <p
          data-layername="weBelieveWorkingCanBeFunWeMakeEffortsToMakeItFunWorkIsWhereYouSpendMostOfYourDayAtAndHenceNeedsToBeEnjoyedAtZenitheumWeCelebrateWorkWeValueBothPersonalAndProfessionalLivesOfOurEmployeesAndFindOurselvesInAnUrgeToCreateAHealthyWorkEnvironmentBeAPartOfOurVisionaryTeam"
          className="mt-24 text-2xl max-md:mt-10 max-md:max-w-full"
        >
          We believe working can be fun. We make efforts to make it fun. Work is
          where you spend most of your day at and hence needs to be enjoyed. At
          Zenitheum, we celebrate work. We value both personal and professional
          lives of our employees and find ourselves in an urge to create a
          healthy work environment. Be a part of our visionary team.
        </p>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-24 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 max-md:mt-10"
        >
          Follow on linkedin
        </button>
      </div>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/6adf65a5c38ad373d021a1d0cae19753fda6353c6dc996e4e41be4f81fb25844?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
        alt="Life at Zenitheum"
        className="object-contain grow shrink self-stretch my-auto aspect-[1.32] min-w-[240px] w-[1106px] max-md:max-w-full"
      />
    </section>
  );
}

export default LifeAtZenitheum;
