/**
 * This code was generated by Rushikesh
 */

import React from "react";
import LifeImage from "../../images/LifeAtZenitheum.png";

function LifeAtZenitheum() {
  return (
    <section
      data-layername="lifeAtZenitheum"
      className="flex gap-10 items-center px-20 py-28 w-full text-white border-t border-b border-zinc-700 max-w-[1920px] max-md:pl-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="lifeAtZ"
        className="flex flex-col grow shrink justify-center w-[30%] max-md:max-w-full"
      >
        <h2
          data-layername="lifeAtZenitheum"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Life at Zenitheum
        </h2>
        <p
          data-layername="weBelieveWorkingCanBeFunWeMakeEffortsToMakeItFunWorkIsWhereYouSpendMostOfYourDayAtAndHenceNeedsToBeEnjoyedAtZenitheumWeCelebrateWorkWeValueBothPersonalAndProfessionalLivesOfOurEmployeesAndFindOurselvesInAnUrgeToCreateAHealthyWorkEnvironmentBeAPartOfOurVisionaryTeam"
          className="mt-12 text-2xl max-md:mt-10 max-md:max-w-full"
        >
          We believe working can be fun. We make efforts to make it fun. Work is
          where you spend most of your day at and hence needs to be enjoyed. At
          Zenitheum, we celebrate work. We value both personal and professional
          lives of our employees and find ourselves in an urge to create a
          healthy work environment. Be a part of our visionary team.
        </p>
        <a
          href="https://www.linkedin.com/company/zenitheum"
          target="_blank"
          rel="noopener noreferrer"
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-12 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 max-md:mt-10"
        >
          Follow on linkedin
        </a>
      </div>
      <img
        loading="lazy"
        src={LifeImage}
        alt="Life at Zenitheum"
        className="object-cover grow shrink aspect-[1.47] w-[50%] rounded-[100px] max-md:max-w-full"
      />
    </section>
  );
}

export default LifeAtZenitheum;
