/**
 * This code was generated by Builder.io
 */
import React from "react";

const socialLinks = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6f8347fa28e6c597a51142c106a5c91a112ca54bca0519a6156481fba08c0385?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Facebook",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9645fbe951416489c3946599f9a4880e5e04f844b6317c3a9d89b9becf558a41?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Twitter",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3223b85f47c7bf2e68fecf03b55564b9a609e051329cf465ab3258847705a83?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Instagram",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0b92c1b5d24a4ac2cb2eaf6260a93a8a0fca4d8f0fdc0dbafd494f700b5efbf5?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "LinkedIn",
  },
];

function SocialLinks() {
  return (
    <div
      data-layername="divSocialLinkWrapper"
      className="flex flex-wrap gap-6 items-start"
    >
      {socialLinks.map((link, index) => (
        <a
          key={index}
          href="#"
          data-layername="link"
          className="flex items-start w-6 max-w-[24px]"
        >
          <div className="flex justify-center items-start w-6 max-w-[24px]">
            <div className="flex overflow-hidden items-start px-0.5 pt-0.5 pb-1 w-6">
              <img
                loading="lazy"
                src={link.icon}
                alt={link.alt}
                className="object-contain w-5 aspect-square"
              />
            </div>
          </div>
        </a>
      ))}
    </div>
  );
}

export default SocialLinks;
