/**
 * This code was generated by Rushikesh
 */
import React from "react";
import Layout from "../Layout/Layout";
import Header from "../Header/Header";
import Founder from "../Founder/Founder";
import Team from "../Team/Team";
import CoreValues from "../CoreValues/CoreValues";

const AboutUs = () => {
  return (
    <Layout>
      <Header />
      <Founder />
      <Team />
      <CoreValues />
    </Layout>
  );
};

export default AboutUs;
