/**
 * This code was generated by Builder.io
 */
import React from "react";

const contactItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/755e65f35658c35f0bf56c0a583af86cb82869d550b926f2fe2656002afe4c59?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Our Head Office",
    content: "Prathamesh Park, Baner, Pune, 411045",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c5c9f58ecc8d1329f091813377b78bcbfa2113a806dac9ca4627aeacdeb0ac47?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Our Hotline",
    content: "+91 7066497023",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e06681e774818bc705832b93fff7e8a9cc18611d014a41df4b1041918f966398?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Mail Us",
    content:
      "support@zenitheum.com careers@zenitheum.com admin@zenitheum.com rushikesh@zenitheum.com",
  },
];

const ContactInfo = () => {
  return (
    <div className="flex flex-wrap items-start w-full max-md:max-w-full">
      {contactItems.map((item, index) => (
        <div
          key={index}
          data-layername="divSCardBlock"
          className="flex flex-col flex-1 shrink px-5 pt-5 pb-10 border-r basis-0 border-zinc-700 min-h-[304px] min-w-[240px] max-md:max-w-full"
        >
          <div
            data-layername="divSCardIcon"
            className="flex overflow-hidden justify-center items-center px-5 w-16 h-16 bg-neutral-800 rounded-[32px]"
          >
            <img
              loading="lazy"
              src={item.icon}
              alt={`${item.title} icon`}
              className="object-contain self-stretch my-auto w-7 aspect-square"
            />
          </div>
          <div
            data-layername="divSCardText"
            className="flex flex-col mt-4 w-full"
          >
            <h3
              data-layername={item.title.toLowerCase().replace(/\s+/g, "")}
              className="text-3xl font-medium leading-none text-zinc-300"
            >
              {item.title}
            </h3>
            <p
              data-layername="pSCardParagraph"
              className="flex-1 shrink pr-5 mt-3.5 w-full text-lg leading-7 text-white whitespace-pre-line"
            >
              {item.content}
            </p>
          </div>
        </div>
      ))}
    </div>
  );
};

export default ContactInfo;
