/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Web3 Consultant at Zenitheum
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description:
            </h2>
            <p className="mt-4">
              We are looking for a passionate and motivated Web3 and AI Research
              Consultant (Intern) to join our team. The ideal candidate will
              have a keen interest in the latest developments in Artificial
              Intelligence (AI) or Web3 technologies. You will primarily focus
              on researching various domains such as DeFi (Decentralized
              Finance), DeSo (Decentralized Social Networks), Blockchain
              Analytics, and other emerging fields. The role involves
              documenting findings, analyzing data, and creating presentations
              for both technical and non-technical stakeholders.
            </p>
            <p className="mt-4">
              This internship offers a unique opportunity to explore
              cutting-edge technologies and gain hands-on experience in AI and
              Web3, while contributing to the strategic research efforts of our
              organization.
            </p>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ol className="list-decimal list-inside mt-4">
              <li>Research and Analysis:</li>
            </ol>
            <ul className="list-disc list-inside ml-8">
              <li>
                Conduct in-depth research on various AI mains including but not
                limited to DeFi, DeSo, Blockchain Analytics, and other
                decentralized technologies.
              </li>
              <li>
                Stay updated with the latest trends, developments, and
                innovations in AI and blockchain technology.
              </li>
              <li>
                Analyze and summarize complex technical information and insights
                for various target audiences.
              </li>
            </ul>
            <ol start="2" className="list-decimal list-inside mt-4">
              <li>Documentation and Reporting:</li>
            </ol>
            <ul className="list-disc list-inside ml-8">
              <li>
                Organize and document all gathered research in a structured and
                clear manner.
              </li>
              <li>
                Prepare detailed reports and white papers based on research
                findings.
              </li>
              <li>
                Ensure all documentation is up-to-date and easily accessible to
                the team.
              </li>
            </ul>
            <ol start="3" className="list-decimal list-inside mt-4">
              <li>Presentation Development:</li>
            </ol>
            <ul className="list-disc list-inside ml-8">
              <li>
                Create engaging and informative presentations based on research
                findings for both technical and non-technical audiences.
              </li>
              <li>
                Tailor content to suit different audiences, from executives to
                engineers, highlighting the impact of Web3 and AI technologies.
              </li>
            </ul>
            <ol start="4" className="list-decimal list-inside mt-4">
              <li>Collaboration:</li>
            </ol>
            <ul className="list-disc list-inside ml-8">
              <li>
                Work closely with senior consultants and experts to develop
                in-depth insights.
              </li>
              <li>
                Engage in collaborative discussions to enhance the scope and
                depth of research projects.
              </li>
            </ul>
            <h3 className="text-4xl mt-8">Qualifications:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>
                Currently pursuing or recently completed a degree in Computer
                Science, Data Science, AI, Blockchain Technology, or related
                fields.
              </li>
              <li>
                Basic understanding of AI, blockchain technologies, and Web3
                applications (DeFi, DeSo, etc.).
              </li>
              <li>
                Strong analytical and research skills with the ability to
                synthesize information effectively.
              </li>
              <li>
                Proficiency in technical writing and the ability to present
                complex ideas clearly.
              </li>
              <li>
                Familiarity with presentation tools such as PowerPoint, Google
                Slides, etc.
              </li>
              <li>
                Excellent communication skills with the ability to adapt content
                for both technical and non-technical audiences.
              </li>
              <li>
                Self-motivated and capable of working independently as well as
                in a team environment.
              </li>
            </ul>
            <h3 className="text-4xl mt-8">Preferred Skills:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>
                Basic knowledge of programming languages such as Python,
                Solidity, or JavaScript.
              </li>
              <li>
                Understanding of blockchain platforms such as Ethereum, Bitcoin,
                or others.
              </li>
              <li>
                Familiarity with AI concepts such as machine learning, natural
                language processing, or computer vision.
              </li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>
                Hands-on experience working with cutting-edge technologies in AI
                and Web3.
              </li>
              <li>
                Mentorship from industry experts in AI, blockchain, and
                decentralized systems.
              </li>
              <li>
                Opportunity to contribute to research that will shape future
                business strategies.
              </li>
              <li>Flexible working environment with remote work options.</li>
            </ul>
            <p className="mt-8">
              If you are passionate about exploring the intersection of AI and
              Web3 and eager to contribute to innovative research, we encourage
              you to apply!
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
