/**
 * This code was generated by Builder.io
 */
import React from "react";
import Footer from "./Footer";
import JobContent from "./JobContent";
import { useEffect } from 'react';

function JobDescription() {
  useEffect(() => {
    window.scrollTo(0,0);
  }, []);

  return (
    <div
      data-layername="jobDescription"
      className="flex overflow-hidden flex-col pb-32 bg-zinc-900 max-md:pb-24"
    >
      <main
        data-layername="main"
        className="flex flex-col mt-0 w-full max-md:max-w-full"
      >
        <JobContent />
      </main>
      <Footer />
    </div>
  );
}

export default JobDescription;
