/**
 * This code was generated by Builder.io
 */
import React from "react";
import { useNavigate } from "react-router-dom";

function CoreValues() {
  const navigate = useNavigate();

  const handleViewServices = () => {
    navigate('/contactus'); 
  };
  return (
    <section
      data-layername="letsWorkTogether"
      className="flex overflow-hidden justify-center items-center px-28 py-11 w-full text-white min-h-[553px] max-md:px-5 max-md:max-w-full"
    >
      <div
        data-layername="divCtaH1stLine"
        className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
      >
        <h2
          data-layername="ourCoreValues"
          className="text-9xl font-medium leading-none text-center max-md:max-w-full max-md:text-4xl"
        >
          Our Core Values
        </h2>
        <p
          data-layername="weAreCommittedToIntegrityInnovationAndCollaborationBelievingThatThesePrinciplesDriveProgressBothWithinOurCompanyAndForOurClientsWeBelieveInContinuousLearningAndAdaptabilityEnsuringThatWeStayAtTheForefrontOfTechnologyByFosteringACultureOfInclusivityAndRespectWeEmpowerOurTeamToPushBoundariesAndChallengeTheStatusQuoUltimatelyDeliveringExceptionalResultsThatAlignWithOurClientsGoals"
          className="mt-16 text-2xl text-center w-[986px] max-md:mt-10 max-md:max-w-full"
        >
          We are committed to integrity, innovation, and collaboration,
          believing that these principles drive progress both within our company
          and for our clients. We believe in continuous learning and
          adaptability, ensuring that we stay at the forefront of technology. By
          fostering a culture of inclusivity and respect, we empower our team to
          push boundaries and challenge the status quo, ultimately delivering
          exceptional results that align with our clients' goals.
        </p>
        <button
          data-layername="button"
          className="justify-center py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label="Get in Touch"
        >
          Get in Touch
        </button>
      </div>
    </section>
  );
}

export default CoreValues;
