/**
 * This code was generated by Rushikesh
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center px-28 py-20 w-full max-md:px-5 max-md:max-w-full"
      >
        <div
          data-layername="AboutUsContainer"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch w-[75%] basis-0 max-md:max-w-full"
        >
          <h1
            data-layername="aboutUs"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            About Us
          </h1>
          <p
            data-layername="Description"
            className="mt-16 text-2xl border border-black border-solid max-md:mt-10 max-md:max-w-[75%] max-md:text-2xl"
          >
            We specialize in harnessing the transformative potential of
            cutting-edge technologies, with a primary focus on Blockchain Data
            Analytics and Artificial Intelligence. Our mission is to pave the
            way for a more innovative and interconnected world, where businesses
            and individuals thrive through secure and seamless technology
            solutions. Through our comprehensive range of services and
            expertise, we are committed to delivering tangible value and
            empowering our clients to embrace the future with confidence.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
