/**
 * This code was generated by Builder.io
 */
import React from "react";
import founderImage from "../../images/founder.jpg";

function MeetTheFounder() {
  return (
    <section
      data-layername="meetTheFounder"
      className="flex flex-wrap gap-10 items-center pr-14 pl-16 mt-32 w-full border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
        className="flex flex-col grow shrink justify-center self-stretch my-auto text-white min-w-[240px] w-[389px] max-md:max-w-full"
      >
        <h2
          data-layername="meetTheFounder"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Meet the Founder!
        </h2>
        <p
          data-layername="myVisionToSteerZenitheumToTheForefrontOfTheBlockchainAndAiSolutionsIndustryComesFromMyBackgroundAsADataScientistWithTheRapidTechnologicalDevelopmentsGoingOnInBl0CkchainAndAiDomainIFeelAnUrgeToHelpCompaniesUnderstandAndIntegrateTheseTechnologiesToTheirBusinessWeAtZenitheumAreDeterminedToInstallTheNextBlockOfTechnologyToYourChainOfSuccessRushikeshChopadeFounderAndCeoZenitheum"
          className="mt-24 text-2xl max-md:mt-10 max-md:max-w-full"
        >
          My vision to steer Zenitheum to the forefront of the blockchain and AI
          solutions industry comes from my background as a Data Scientist. With
          the rapid technological developments going on in Bl0ckchain and AI
          domain, I feel an urge to help companies understand and integrate
          these technologies to their business. We, at Zenitheum, are determined
          to install the next "Block" of technology to your "Chain" of
          success....
          <br />
          <br />
          Rushikesh Chopade,
          <br />
          Founder and CEO,
          <br />
          Zenitheum
        </p>
        <a
          href="https://www.linkedin.com/company/zenitheum"
          target="_blank"
          rel="noopener noreferrer"
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-24 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 max-md:mt-10"
        >
          Follow on linkedin
        </a>
      </div>
      <div
        data-layername="divWNode99Feaec272B08085F1A2Bbf1C421530E9671Bbb9"
        className="flex flex-wrap grow shrink items-start self-stretch pt-7 pb-16 my-auto min-h-[912px] min-w-[240px] w-[1106px] max-md:max-w-full"
      >
        <img
          loading="lazy"
          src={founderImage}
          alt="Founder of Zenitheum"
          className="object-contain grow shrink aspect-[1.47] min-w-[240px] rounded-[100px] w-[962px]"
        />
      </div>
    </section>
  );
}

export default MeetTheFounder;
