/**
 * This code was generated by Rushikesh
 */
import React from "react";
import founderImage from "../../images/founder.jpg";

function MeetTheFounder() {
  return (
    <section
      data-layername="meetTheFounder"
      className="flex flex-wrap gap-10 items-center px-20 py-20 w-full border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="FounderText"
        className="flex flex-col grow shrink justify-center self-stretch text-white min-w-[240px] w-[25%] max-md:max-w-full"
      >
        <h2
          data-layername="FounderHeading"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Meet the Founder!
        </h2>
        <p
          data-layername="Description"
          className="mt-24 text-2xl max-md:mt-10 max-md:max-w-full"
        >
          My vision to steer Zenitheum to the forefront of the blockchain and AI
          solutions industry comes from my background as a Data Scientist. With
          the rapid technological developments going on in Bl0ckchain and AI
          domain, I feel an urge to help companies understand and integrate
          these technologies to their business. We, at Zenitheum, are determined
          to install the next "Block" of technology to your "Chain" of
          success....
          <br />
          <br />
          Rushikesh Chopade,
          <br />
          Founder and CEO,
          <br />
          Zenitheum
        </p>
        <a
          href="https://www.linkedin.com/in/rushikesh3388/"
          target="_blank"
          rel="noopener noreferrer"
          data-layername="button"
          className="justify-center text-center py-4 w-fit pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
        >
          Follow on linkedin
        </a>
      </div>
      <div
        data-layername="ImageLayer"
        className="flex flex-wrap grow shrink items-start self-stretch w-[55%] max-md:max-w-full"
      >
        <img
          loading="lazy"
          src={founderImage}
          alt="Founder of Zenitheum"
          className="object-cover grow shrink aspect-[1.47] min-w-[240px] rounded-[100px]"
        />
      </div>
    </section>
  );
}

export default MeetTheFounder;
