/**
 * This code was generated by Builder.io
 */
import React, { useState } from "react";
import SabaleImage from "../../images/sabale.png";
import AvinashImage from "../../images/avinash.png";
import NachiketImage from "../../images/nachiket.png";

const teamMembers = [
  {
    name: "Rushikesh Sabale",
    position: "Product Manager, Zenitheum",
    image:SabaleImage,
  },
  {
    name: "Avinash Ingle",
    position: "Chief Operating Officer, Zenitheum",
    image:AvinashImage,
  },
  {
    name: "Nachiket Tekade",
    position: "Full-Stack Developer, Zenitheum",
    image:NachiketImage,
  },
];


function OurTeam() {
  const [currentIndex, setCurrentIndex] = useState(0);

  const handlePrevClick = () => {
    setCurrentIndex((currentIndex - 1 + teamMembers.length) % teamMembers.length);
  };

  const handleNextClick = () => {
    setCurrentIndex((currentIndex + 1) % teamMembers.length);
  };

  return (
    <section
      data-layername="ourTeam"
      className="flex relative gap-20 px-10 py-20 w-full text-white border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="ImageContainer"
        className="flex z-0 flex-wrap items-start h-full w-[55%] max-md:max-w-full"
      >
        <div
          className="flex relative grow shrink items-start border border-solid border-zinc-700 min-h-[456px] min-w-[240px] w-[962px] max-md:max-w-full"
        >
          <div className="absolute top-0 left-0 w-full h-full flex justify-between items-center">
            <button
              className="text-7xl cursor-pointer"
              onClick={handlePrevClick}
            >
              &#60;
            </button>
            <img
              loading="lazy"
              src={teamMembers[currentIndex].image}
              alt={`${teamMembers[currentIndex].name} - ${teamMembers[currentIndex].position}`}
              className="object-cover z-0 rounded-xl aspect-[1.32] min-w-[240px] w-[601px] max-md:max-w-full"
            />
            <button
              className="text-7xl cursor-pointer"
              onClick={handleNextClick}
            >
              &#62;
            </button>
          </div>
          <div
            data-layername="divSCardBlock"
            className="flex absolute bottom-10 z-0 flex-col left-[23px] max-w-[300px] min-w-[240px] w-[300px]"
          >
            <div data-layername="divSCardText" className="flex flex-col">
              <div
                data-layername={teamMembers[currentIndex].name.toLowerCase().replace(" ", "")}
                className="gap-2.5 self-start px-2.5 py-1.5 text-3xl font-medium leading-none"
              >
                {teamMembers[currentIndex].name}
              </div>
              <div
                data-layername="pSCardParagraph"
                className="px-2.5 mt-2.5 text-lg leading-loose"
              >
                {teamMembers[currentIndex].position}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        data-layername="TeamTextContainer"
        className="flex z-0 flex-col justify-center my-auto w-[45%] max-md:max-w-full"
      >
        <h2
          data-layername="ourTeam"
          className="text-6xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
        >
          Our Team
        </h2>
        <p
          data-layername="Description"
          className="mt-12 text-2xl max-md:mt-10 max-md:max-w-full"
        >
          Our diverse and dynamic team is the heart of our success. Comprising
          exceptional talents from various areas of expertise, we unite under a
          common vision to drive innovation and excellence. With deep expertise
          in Blockchain, Data Engineering, and AI, our collaborative spirit
          fuels groundbreaking solutions that propel our clients towards their
          goals. Together, we are committed to shaping a brighter future
          empowered by technology and fostering meaningful connections on a
          global scale.
        </p>
      </div>
    </section>
  );
}

export default OurTeam;
