/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import ResearchExperience from "./ResearchExperience";
import Footer from "./Footer";

function ResearchPublications() {
  return (
    <div
      data-layername="researchPublications"
      className="flex overflow-hidden flex-col pb-32 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col w-full min-h-[3621px] max-md:max-w-full"
      >
        <ResearchExperience />
      </main>
      <Footer />
    </div>
  );
}

export default ResearchPublications;
