/**
 * This code was generated by Builder.io
 */
import React from "react";
import BlockchainAnalyticsServices from "./BlockchainAnalyticsServices";
import Footer from "./Footer";
import LetsWorkTogether from "./LetsWorkTogether";


function Services() {
  return (
    <div
      data-layername="services"
      className="flex overflow-hidden flex-col pb-56 bg-zinc-900 max-md:pb-24"
    >
      <main
        data-layername="main"
        className="flex flex-col w-full max-md:max-w-full"
      >
        <BlockchainAnalyticsServices />  
        <LetsWorkTogether />
        <Footer />
      </main>
    </div>
  );
}

export default Services;
