/**
 * This code was generated by Builder.io
 */
import React from "react";
import { useNavigate } from "react-router-dom";

function LetsWorkTogether() {
  const navigate = useNavigate();

  const handleViewServices = () => {
    navigate('/contactus'); 
  };
  return (
    <main className="flex overflow-hidden justify-center items-center text-white">
      <section className="flex overflow-hidden flex-col justify-center py-20 items-center self-stretch max-md:max-w-full">
        <h1 className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:max-w-full max-md:text-4xl max-md:leading-[50px]">
           Explore Blockchain Integration
        </h1>
        <p className="mt-9 text-2xl text-center w-[65%] max-md:max-w-full">
          Take the first step towards a transformative future by partnering with
          us today. Explore our cutting-edge solutions in Blockchain, Data
          Engineering, and AI, and experience the power of innovation and
          seamless connectivity. Contact us now for a personalized consultation,
          and together, let's build a brighter tomorrow. Your success awaits!
        </p>
        <button
          data-layername="button"
          className="justify-center py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label="Book a Service"
        >
          Get in Touch
        </button>
      </section>
    </main>
  );
}

export default LetsWorkTogether;
