/**
 * This code was generated by Builder.io
 */
import React from "react";
import { useNavigate } from "react-router-dom";

const ServiceSection = ({
  title,
  description,
  buttonText,
  imageSrc,
  imageAlt,
  reverse = false,
}) => {
  const contentClass = reverse ? "order-2" : "order-1";
  const imageClass = reverse ? "order-1" : "order-2";
  
  const navigate = useNavigate();
  const handleViewServices = () => {
    navigate('/contactus'); 
  };

  return (
    <div
      className={`flex flex-wrap gap-20 py-24 px-20 items-center text-white border-t border-b border-zinc-700 max-md:px-5 max-md:mt-10`}
    >
      <div
        className={`flex flex-col grow shrink justify-center w-[25%] self-stretch min-w-[240px] max-md:max-w-full ${contentClass}`}
      >
        <h2 className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]">
          {title}
        </h2>
        <p className="mt-10 text-2xl max-md:max-w-full">{description}</p>
        <button
          data-layername="button"
          className="justify-center text-center py-4 w-fit pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label={buttonText}
        >
          {buttonText}
        </button>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className={`object-cover grow shrink self-stretch w-[45%] aspect-[1.47] min-w-[240px] rounded-[100px] max-md:max-w-full ${imageClass}`}
      />
    </div>
  );
};

export default ServiceSection;
