/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";

const Layout = ({ children }) => {
  return (
    <div className="flex overflow-hidden flex-col pb-44 bg-zinc-900 max-md:pb-24">
      <Navbar />
      <main>{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
