/**
 * This code was generated by Builder.io
 */
import React from "react";

const ContactSection = () => {
  return (
    <section className="flex overflow-hidden justify-center items-center px-28 py-14 w-full text-white min-h-[553px] max-md:px-5 max-md:max-w-full">
      <div className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
        <h2 className="text-9xl font-medium leading-none text-center max-md:max-w-full max-md:text-4xl">
          Book an Appointment
        </h2>
        <p className="mt-16 text-2xl text-center w-[986px] max-md:mt-10 max-md:max-w-full">
          Take the first step towards a transformative future by partnering with
          us today. Explore our cutting-edge solutions in Blockchain, Data
          Engineering, and AI, and experience the power of innovation and
          seamless connectivity. Contact us now for a personalized consultation,
          and together, let's build a brighter tomorrow. Your success awaits!
        </p>
        <a
          href="#contact"
          className="py-4 px-8 mt-16 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 max-md:mt-10"
        >
          Contact us
        </a>
      </div>
    </section>
  );
};

export default ContactSection;
