/**
 * This code was generated by Builder.io
 */
import React from "react";

const socialLinks = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6f8347fa28e6c597a51142c106a5c91a112ca54bca0519a6156481fba08c0385?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Facebook",
    href: "#",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/28896cb0a659fd9af4e97666e55694f1937591a3ad64260d31c80782de576530?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Twitter",
    href: "#",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c3223b85f47c7bf2e68fecf03b55564b9a609e051329cf465ab3258847705a83?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "Instagram",
    href: "#",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/700b286c489b51a633d94573ec13fffd24e41adfaf155aa6d8a91d032cb00143?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    alt: "LinkedIn",
    href: "#",
  },
];

const SocialLinks = () => {
  return (
    <div className="flex flex-wrap gap-6 items-start">
      {socialLinks.map((link, index) => (
        <a
          key={index}
          href={link.href}
          className="flex items-start w-6 max-w-[24px]"
          aria-label={`Visit our ${link.alt} page`}
        >
          <div className="flex justify-center items-start w-6 max-w-[24px]">
            <div className="flex overflow-hidden items-start px-0.5 pt-0.5 pb-1 w-6">
              <img
                loading="lazy"
                src={link.icon}
                alt={link.alt}
                className="object-contain w-5 aspect-square"
              />
            </div>
          </div>
        </a>
      ))}
    </div>
  );
};

export default SocialLinks;
