/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Web3 Business Analyst
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description: 
            </h2>
            <h3 className="text-4xl mt-8">(Internship, Duration: 2 months)</h3>
            <h3 className="text-4xl mt-8">Position Overview</h3>
            <li className="mt-4">
            We are looking for a highly motivated Web3 Business Analyst to join our team. The role involves conducting extensive research, preparing impactful presentations, and developing case studies around the latest advancements in Web3. 
            <br />
            The ideal candidate has a solid understanding of Web3 concepts, their applications across industries, and the ability to deliver actionable insights to support strategic decision-making.
            </li>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Conduct in-depth research on Web3 trends, including blockchain, smart contracts, DeFi, NFTs, and Blockchain Analytics</li>
              <li>Develop detailed case studies exploring the practical applications of Web3 in various industries</li>
              <li>Create professional, easy-to-understand presentations for diverse stakeholders.</li>
              <li>Collaborate with teams to align Web3 opportunities with business goals.</li>
              <li>Stay updated on Web3 innovations and assess their potential business impact.</li>
            </ul>
            <h3 className="text-4xl mt-8">Skills Required:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Strong knowledge of Web3 technologies and their applications in industries such as finance, healthcare, gaming, and more.</li>
              <li>Excellent research and analytical skills, with the ability to distill complex concepts into actionable insights.</li>
              <li>Exceptional communication and presentation skills, with experience using tools like PowerPoint or similar platforms.</li>
              <li>Proficiency in Project Management tools like Jira, Confluence, or willing to explore them.</li>
              <li>Familiarity with tokenomics, Smart Contracts, and decentralized governance models.</li>
              <li>Prior experience in Web3, blockchain, or related fields is a plus. </li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Be part of a cutting-edge team working on transformative Web3 projects.</li>
              <li>Mentorship from industry professionals.</li>
              <li>Opportunities for continuous learning and professional development in a fast-evolving industry.</li>
              <li>Certificate of internship and Experience Letter upon completion.</li>
            </ul>
            <h3 className="text-4xl mt-8">How to Apply</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Submit your resume and cover letter to the email address: careers@zenitheum.com OR </li>
              <li>Submit the form on our website: https://zenitheum.com/contactus </li>
            </ul>
            <h3 className="text-4xl mt-8">Application Deadlines</h3>
            <ul className="list-disc list-inside mt-4">
              <li>28th Nov, 2024 </li>
            </ul>
            <br />
            <h3 className="text-4xl mt-8">Even if you do not meet all the requirements, feel free to get in touch with us. We believe in learning as we go. </h3>
            <h3 className="text-4xl mt-8">Join us at Zentiheum and be a part of the AI revolution!</h3>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
