/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import ServiceSection from "./ServiceSection";
import Footer from "./Footer";

const BlockchainAnalyticsServices = () => {
  return (
    <div
      data-layername="blockchainAnalyticsServices"
      className="flex overflow-hidden flex-col pb-52 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col w-full max-md:max-w-full"
      >
        <header
          data-layername="header"
          className="flex flex-col items-center w-full text-center text-white max-w-[1920px] max-md:max-w-full"
        >
          <div
            data-layername="divCta"
            className="flex overflow-hidden justify-center items-center py-20 pr-28 pl-28 w-full min-h-[553px] max-md:px-5"
          >
            <div
              data-layername="divCtaH1stLine"
              className="flex overflow-hidden flex-col flex-1 shrink justify-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
            >
              <h1
                data-layername="blockchainAnalyticsServices"
                className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
              >
                Blockchain Analytics Services
              </h1>
              <p
                data-layername="blockchainAnalyticsServicesAtZenitheumOfferInnovativeSolutionsTailoredToMeetTheEvolvingDemandsOfTheDigitalLandscapeOurAdvancedOfferingsIncludeCustomizableSmartContractsThatEmpowerYourBusinessWithEnhancedDataInsightsWithAFocusOnBlockchainDataVisualizationAndCustomAnalyticsSolutionsWeEnsureThatYourOrganizationCanMakeInformedDecisionsBackedByRobustDataAnalysis"
                className="self-center mt-16 text-2xl w-[986px] max-md:mt-10 max-md:max-w-full"
              >
                Blockchain Analytics services at Zenitheum offer innovative
                solutions tailored to meet the evolving demands of the digital
                landscape. Our advanced offerings include customizable smart
                contracts that empower your business with enhanced data
                insights. With a focus on blockchain data visualization and
                custom analytics solutions, we ensure that your organization can
                make informed decisions backed by robust data analysis.
              </p>
            </div>
          </div>
        </header>

        <ServiceSection
          title="Smart Contracts for Blockchain Data Analytics"
          description="By designing smart contracts for Data sharing agreements, tracking the origin of your assets/products, And automating of complex data analytics tasks, we provide state-of-the-art support to our clients."
          buttonText="Explore the scope"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/cbf133724a91701f5da280add89737bbc560a4876fed3b4d33e00f7087cab1e9?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          imageAlt="Smart Contracts visualization"
        />

        <ServiceSection
          title="Blockchain Data Mining and AI Modelling"
          description="Make smarter business decisions with well-informed decisions based on blockchain data. We do the in-depth analysis empowering you to make smart decisions faster."
          buttonText="Explore the scope"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/234509b1bbacf56d4af06a5f72d390bf2525b62114a7cdc7be8fc7dfb1f22e03?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          imageAlt="Data Mining and AI Modelling illustration"
          reverse={true}
        />

        <ServiceSection
          title="Blockchain Data Visualization"
          description="Streamline your operations and gain a competitive edge by visualizing blockchain data effectively."
          buttonText="request a Demo"
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/d0dbe2931f170825c796853933f74db993371723b7db34cbc8641d8f7b9f7010?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          imageAlt="Blockchain Data Visualization example"
        />

        <div
          data-layername="dataIndexingSolutions"
          className="flex flex-wrap gap-10 items-center pr-28 mt-32 w-full border-t border-b border-zinc-700 max-w-[1900px] max-md:pr-5 max-md:mt-10 max-md:max-w-full"
        >
          <div
            data-layername="divWNode99Feaec272B08085F1A2Bbf1C421530E9671Bbb9"
            className="flex flex-wrap grow shrink justify-center items-center self-stretch my-auto border-l border-zinc-700 min-w-[240px] w-[1106px] max-md:max-w-full"
          >
            <div className="flex justify-center items-center self-stretch my-auto min-w-[240px] w-[1113px]">
              Continuing from where we left off:
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/21579a235d1021824c99aead6d8015ddfdb87f2de8877054957d7f5b5ddc9c95?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                alt="Data Indexing Solutions visualization"
                className="object-contain self-stretch my-auto aspect-[1.06] min-w-[240px] rounded-[99px] w-[1113px]"
              />
            </div>
          </div>
          <div
            data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
            className="flex flex-col grow shrink justify-center self-stretch my-auto text-white min-w-[240px] w-[389px] max-md:max-w-full"
          >
            <h2
              data-layername="dataIndexingSolutions"
              className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
            >
              Data Indexing Solutions
            </h2>
            <p
              data-layername="ourDataIndexingSolutionsAreAHeavenForDevelopersToBuildTheirCustomApIsAndFasterDataRetrievalFromBlockchain"
              className="mt-10 text-2xl max-md:max-w-full"
            >
              Our data indexing solutions are a heaven for developers to build
              their custom APIs and faster data retrieval from blockchain.
            </p>
            <button
              data-layername="button"
              className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5"
            >
              Request a DEMO
            </button>
          </div>
        </div>

        <div
          data-layername="mergeWeb3"
          className="flex flex-wrap gap-10 items-center pr-24 pl-24 mt-32 max-w-full text-white border-t border-b border-zinc-700 w-[1924px] max-md:px-5 max-md:mt-10"
        >
          <div
            data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
            className="flex flex-col grow shrink justify-center self-stretch my-auto min-h-[718px] min-w-[240px] w-[437px] max-md:max-w-full"
          >
            <h2
              data-layername="mergeWeb3IntoYourBusinessTo"
              className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
            >
              Merge Web3 into your business to...
            </h2>
            <ul
              data-layername="increaseBrandEngagementByBuildingYourOwnNftCollectionAndAdoptRevenueSharingModelInsteadOfTraditionalMarketingModelExpandBusinessesToRegionsFacingRestrictedLimitedInternetAccessGiveYourCustomersPowerOverTheirDataOfferingEnhancedBrandTrustAndGreaterEngagementOptimizeBusinessOperationsLikeBudgetingSupplyChainManagementManufacturingAndAuditingWithWeb3Integration"
              className="mt-10 text-2xl max-md:max-w-full list-disc pl-5"
            >
              <li>
                Increase Brand Engagement by building your own NFT collection
                and adopt revenue sharing model instead of traditional marketing
                model
              </li>
              <li>
                Expand businesses to regions facing restricted limited internet
                access
              </li>
              <li>
                Give your customers power over their data offering enhanced
                brand trust and greater engagement.
              </li>
              <li>
                Optimize business operations like budgeting, supply chain
                management, manufacturing, and auditing with Web3 integration
              </li>
            </ul>
            <button
              data-layername="button"
              className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5"
            >
              explore the scope
            </button>
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/44aabf9d84fd1ea3bcb1dcbaa84982dc8471480ce2f441ef09c94a594389ade4?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
            alt="Web3 integration visualization"
            className="object-contain grow shrink self-stretch my-auto aspect-[1.05] min-w-[240px] rounded-[100px] w-[965px] max-md:max-w-full"
          />
        </div>

        <Footer />
      </main>
    </div>
  );
};

export default BlockchainAnalyticsServices;
