/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Header from "./Header";
import ServiceSection from "./ServiceSection";
import Footer from "./Footer";

function Services() {
  return (
    <div
      data-layername="services"
      className="flex overflow-hidden flex-col pb-56 bg-zinc-900 max-md:pb-24"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col w-full min-h-[4230px] max-md:max-w-full"
      >
        <Header />
        <ServiceSection
          title="Blockchain Analytics Services"
          description="Wide Range of Blockchain Analytics Solutions... Choose the one that meets your requirement or let us know in case of a related requirement, our dedicated team is ready for the battle..."
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/c7dc88af9275c86cff775f8892429bdeb3d9ff19e6a46c26a08c3a528f64bdd1?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          imageAlt="Blockchain Analytics Services Illustration"
          isReversed={false}
        />
        <ServiceSection
          title="AI Services"
          description="We delve into the intricacies of devising advanced Machine Learning and Deep Learning algorithms tailored for various business applications. Our offerings are designed to enhance operational efficiency and provide actionable insights, propelling companies towards their strategic objectives."
          imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/5b86d8f72258bea58718ed7a03f69dcaa8300fec4d9dc4570e5148a441cb62f2?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
          imageAlt="AI Services Illustration"
          isReversed={true}
        />
        <Footer />
      </main>
    </div>
  );
}

export default Services;
