/**
 * This code was generated by Builder.io
 */
import React from "react";

const footerCards = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/755e65f35658c35f0bf56c0a583af86cb82869d550b926f2fe2656002afe4c59?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Our Head Office",
    content: "Prathamesh Park, \nBaner, Pune, 411045",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4d28b6ce24d2ea7598814d3d9c70dba8655e6783a82151e4eeb4cb02c4978300?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Our Hotline",
    content: "+91 7066497023",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/13abfacbd2b720070c88079c726537f6adfffb3ddd78c19d26487a8689b994f5?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    title: "Mail Us",
    content:
      "support@zenitheum.com \ncareers@zenitheum.com \nadmin@zenitheum.com \nrushikesh@zenitheum.com",
  },
];

function FooterCard({ icon, title, content }) {
  return (
    <div
      data-layername="divSCardBlock"
      className="flex flex-col flex-1 shrink px-5 pt-5 pb-10 border-r basis-0 border-zinc-700 min-h-[304px] min-w-[240px] max-md:max-w-full"
    >
      <div
        data-layername="divSCardIcon"
        className="flex overflow-hidden justify-center items-center px-5 w-16 h-16 bg-neutral-800 rounded-[32px]"
      >
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain self-stretch my-auto w-7 aspect-square"
        />
      </div>
      <div data-layername="divSCardText" className="flex flex-col mt-4 w-full">
        <div
          data-layername={title.toLowerCase().replace(/\s+/g, "")}
          className="text-3xl font-medium leading-none text-zinc-300"
        >
          {title}
        </div>
        <div
          data-layername="pSCardParagraph"
          className="flex-1 shrink pr-5 mt-3.5 w-full text-lg leading-7 text-white whitespace-pre-line"
        >
          {content}
        </div>
      </div>
    </div>
  );
}

function FooterCards() {
  return (
    <div className="flex flex-wrap items-start w-full max-md:max-w-full">
      {footerCards.map((card, index) => (
        <FooterCard key={index} {...card} />
      ))}
    </div>
  );
}

export default FooterCards;
