/**
 * This code was generated by Builder.io
 */
import React from "react";
import ResearchPaper from "./ResearchPaper";
import ResearchImage from "../../images/research_paper.png";
function ResearchExperience() {
  const researchPapers = [
    { title: "OpenAI's GPT-3/ChatGPT: Suggests & Correct", PaperUrl:"https://ieeexplore.ieee.org/document/10698683/authors#authors" },
    { title: "Addressing Class Imbalance Problem in Semantic Segmentation using Binary Focal Loss", PaperUrl:"https://link.springer.com/chapter/10.1007/978-981-97-3559-4_28"},
    { title: "Cyclical Learning Rates (CLR'S) for Improving Training Accuracies and Lowering Computational Cost", PaperUrl:"https://link.springer.com/chapter/10.1007/978-3-031-34960-7_23#citeas"},
    { title: "K-fold Semi-supervised Self-learning Technique for Image Disease Localization", PaperUrl:"https://link.springer.com/chapter/10.1007/978-981-19-9819-5_49"},
    { title: "Neural Networks for Predicting Severity of Ovarian Carcinomas", PaperUrl:"https://link.springer.com/chapter/10.1007/978-981-19-7660-5_7" },
    { title: "Single shot detector application for image disease localization", PaperUrl:"https://www.biorxiv.org/content/10.1101/2021.09.21.461307v1"},
    { title:"Machine learning for identification and characterization of molecular gene signatures in progression of benign tumors", PaperUrl:"https://dl.acm.org/doi/abs/10.1145/3469213.3469214"}
  ];

  return (
    <section
      data-layername="researchExperience"
      className="flex flex-col w-full text-white"
    >
      <div
        data-layername="frame"
        className="flex overflow-hidden px-20 justify-center items-center w-full max-md:px-5"
      >
        <div
          data-layername="ResearchContainer"
          className="flex overflow-hidden flex-col flex-1 my-40 shrink justify-center items-center self-stretch w-full basis-0"
        >
          <h1
            data-layername="ResearchHeading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Our Research Experience
          </h1>
          <img
            loading="lazy"
            src={ResearchImage}
            alt="AI-ML Research Experience Illustration"
            className="object-cover mt-24 w-[80%] aspect-[1.67] rounded-[100px] max-md:mt-10"
          />
          {researchPapers.map((paper, index) => (
            <ResearchPaper key={index} 
            title={paper.title} 
            PaperUrl={paper.PaperUrl} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default ResearchExperience;
