/**
 * This code was generated by Builder.io
 */
import React from "react";
import ResearchExperience from "./ResearchExperience";
import Footer from "./Footer";
import { useEffect } from 'react';

function ResearchPublications() {
  useEffect(() => {
    window.scrollTo(0,0);
  }, []);
  return (
    <div
      data-layername="researchPublications"
      className="flex overflow-hidden flex-col pb-32 bg-zinc-900 max-md:pb-24"
    >
      <main
        data-layername="main"
        className="flex flex-col w-full max-md:max-w-full"
      >
        <ResearchExperience />
      </main>
      <Footer />
    </div>
  );
}

export default ResearchPublications;
