/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Web3 Data Analyst
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description: 
            </h2>
            <h3 className="text-4xl mt-8">(Internship, Duration: 2 months)</h3>
            <h3 className="text-4xl mt-8">Position Overview</h3>
            <li className="mt-4">
            We are seeking a highly skilled and motivated Web3 Data Analyst to join our team. This role focuses on mining, analyzing, and visualizing blockchain data to provide actionable insights and develop advanced blockchain data indexing solutions. 
            <br />
            As a Web3 Data Analyst, you will play a key role in enhancing our understanding of decentralized ecosystems and driving data-driven decisions within the blockchain space.            </li>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Extract, clean, and analyze on-chain and off-chain blockchain data to identify patterns, trends, and anomalies.</li>
              <li>Develop automated pipelines for real-time blockchain data collection and processing.</li>
              <li>Create interactive and insightful dashboards to represent blockchain data effectively.</li>
              <li>Communicate complex data findings through visual storytelling for stakeholders.</li>
              <li>Build and maintain robust blockchain indexing solutions for scalable data retrieval and query</li>
              <li>Prepare documentation in Jira/Confluence presenting the data findings</li>
            </ul>
            <h3 className="text-4xl mt-8">Skills Required:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Strong proficiency in blockchain technologies and understanding of Web3 ecosystems.</li>
              <li>Experience in data mining, analysis, and visualization tools such as Python, SQL, Tableau, or similar.</li>
              <li>Hands-on experience with blockchain data tools (e.g., The Graph, BigQuery for crypto, Etherscan APIs).</li>
              <li>Proficiency in indexing techniques and querying large blockchain datasets.</li>
              <li>Strong analytical and problem-solving skills with attention to detail.</li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Opportunity to work at the intersection of cutting-edge technologies: AI and blockchain.</li>
              <li>Mentorship from industry professionals.</li>
              <li>Growth opportunities in a fast-paced, innovative startup environment.</li>
              <li>Certificate of internship and Experience Letter upon completion.</li>
            </ul>
            <h3 className="text-4xl mt-8">How to Apply</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Submit your resume and cover letter to the email address: careers@zenitheum.com OR </li>
              <li>Submit the form on our website: https://zenitheum.com/contactus </li>
            </ul>
            <h3 className="text-4xl mt-8">Application Deadlines</h3>
            <ul className="list-disc list-inside mt-4">
              <li>28th Nov, 2024 </li>
            </ul>
            <br />
            <h3 className="text-4xl mt-8">Even if you do not meet all the requirements, feel free to get in touch with us. We believe in learning as we go. </h3>
            <h3 className="text-4xl mt-8">Join us at Zentiheum and be a part of the AI revolution!</h3>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
