/**
 * This code was generated by Builder.io
 */
import React from "react";

const NavTab = ({ label, isActive }) => {
  const baseClasses =
    "overflow-hidden flex-1 shrink gap-2.5 self-stretch py-10 px-12 border-r border-b bg-zinc-900 border-zinc-700 min-h-[100px] max-md:px-5";
  const activeClasses = isActive
    ? "text-blue-700 bg-white border-zinc-900"
    : "";

  return (
    <div data-layername="tab" className={`${baseClasses} ${activeClasses}`}>
      {label}
    </div>
  );
};

export default NavTab;
