/**
 * This code was generated by Builder.io
 */
import React from "react";

const links = [
  "Home",
  "Products",
  "Services",
  "Trainings",
  "Clients",
  "About Us",
  "Research",
  "Careers",
];

function FooterLinks() {
  return (
    <div className="flex flex-col flex-1 shrink self-start basis-[234px] min-w-[240px] max-md:max-w-full">
      <div className="flex flex-col justify-center px-12 py-6 w-full text-2xl leading-none text-white border-b border-zinc-700 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
          {links.map((link, index) => (
            <div key={index} className="gap-2.5 self-stretch whitespace-nowrap">
              {link}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default FooterLinks;
