/**
 * This code was generated by Builder.io
 */
import React from "react";
import Layout from "../components/Layout/Layout";
import Header from "../components/Home/Header";
import ServiceSection from "../components/Home/ServiceSection";
import CallToAction from "../components/Home/CallToAction";

const services = [
  {
    title: "GenAI Innovations",
    description:
      "With the buzz around GenAI language models like Gemini, Claude and ChatGPT, our team holds speciality in integrating these into your business cases as well as designing novel GenAI models. We hold expertise in all genres of GenAI innovations, whether Images, Text, or Speech.",
    buttonText: "Explore the scope",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/c045f4ff7d743ae3ab9b1df85ae224ca3ad5c42009a6bb4767616868d60aca38?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    imageAlt: "GenAI Innovations illustration",
    isReversed: false,
  },
  {
    title: "Business Data Analytics",
    description:
      "Our Business Data Analytics services empower organizations to transform complex data into meaningful strategies... Along with the complex analysis, we also hold expertise in Data Visualization using Tableau and PowerBI",
    buttonText: "Explore the scope",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/444d321979985a8e5b3d3e454563d476969bfb791f42cfaea4a2121635bc9913?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    imageAlt: "Business Data Analytics visualization",
    isReversed: true,
  },
  {
    title: "AI-ML Modelling",
    description:
      "Our dedicated Model Development and Deployment services ensure seamless integration of AI into existing infrastructures. Experience how our AI solutions can significantly transform your business landscape.",
    buttonText: "Explore the scope",
    imageSrc:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/41fe64ecfbab7e638f52a51d7afa0687f47487a34dc07518f338ac63f488ab2a?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22",
    imageAlt: "AI-ML Modelling illustration",
    isReversed: false,
  },
];

function Home() {
  return (
    <Layout>
      <Header />
      {services.map((service, index) => (
        <ServiceSection key={index} {...service} />
      ))}
      <CallToAction />
    </Layout>
  );
}

export default Home;
