/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import ServiceSection from "./ServiceSection";
import MergeWithWeb3 from "./MergeWithWeb3";
import HowWeDoIt from "./HowWeDoIt";

const Home = () => {
  return (
    <>
      <Header />
      <ServiceSection />
      <MergeWithWeb3 />
      <HowWeDoIt />
    </>
  );
};

export default Home;
