/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import WeHelpBusinesses from "./WeHelpBusiness";
import MergeWithWeb3 from "./MergeWithWeb3";
import HowWeDoIt from "./HowWeDoIt";
import BusinessBenifits from "./BusinessBenefits/BusinessBenefits";
import Footer from "./Footer/Footer";
const Home = () => {
  return (
    <>
      <Header />
      <WeHelpBusinesses />
      <MergeWithWeb3 />
      <BusinessBenifits />
      <HowWeDoIt />
      <Footer />
    </>
  );
};

export default Home;
