/**
 * This code was generated by Builder.io
 */
import React from "react";

const MergeWithWeb3 = () => {
  return (
    <section className="flex flex-wrap gap-10 items-center pr-16 pl-32 font-medium tracking-widest text-white min-h-[1061px] max-md:px-5 max-md:mr-2 max-md:max-w-full">
      <p className="grow shrink self-stretch my-auto text-4xl w-[346px] max-md:max-w-full">
        We ace into figuring out the scope of integration of Web3 into your
        business to increase customer engagement and optimize your internal
        business operations. Get in touch with us to figure out the scope.
      </p>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d2a7a542589fa6b37e6911b6083763460964c25d0a3b9c370338945e0f81ef06?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
        alt="Web3 integration illustration"
        className="object-contain grow shrink self-stretch my-auto aspect-[0.81] min-w-[240px] rounded-[101px] w-[565px] max-md:max-w-full"
      />
      <h2 className="grow shrink self-stretch my-auto text-6xl w-[388px] max-md:max-w-full max-md:text-4xl">
        Stay ahead of your competitors with our Digital Transformation Services
        in web3...
      </h2>
    </section>
  );
};

export default MergeWithWeb3;
