/**
 * This code was generated by Builder.io
 */
import React from "react";

const ServiceCard = ({ title, description }) => {
  return (
    <section className="flex overflow-hidden flex-1 shrink justify-center items-center self-start px-28 py-28 border-l basis-0 border-zinc-700 min-h-[456px] min-w-[240px] max-md:px-5 max-md:py-24 max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 max-w-[300px] min-w-[240px] w-[300px]">
        <div className="flex flex-col w-full">
          <h3 className="text-3xl font-medium leading-none text-zinc-300">
            {title}
          </h3>
          <p className="pr-5 mt-3.5 w-full text-lg leading-7 text-white">
            {description}
          </p>
        </div>
      </div>
    </section>
  );
};

export default ServiceCard;
