/**
 * This code was generated by Rushikesh
 */
import React from "react";

const ServiceCard = ({title, description }) => {
  return (
    <div className="flex overflow-hidden grow shrink justify-center items-center self-stretch py-24 pr-28 pl-28 my-auto border-l border-zinc-700 min-h-[456px] min-w-[240px] w-[426px] max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0 max-w-[300px] min-w-[240px]">
        <div className="flex overflow-hidden justify-center items-center px-5 w-16 h-16 bg-neutral-800 rounded-[32px]">
          <img
            loading="lazy"
            src={icon}
            alt={`${title} icon`}
            className="object-contain self-stretch my-auto w-7 aspect-square"
          />
        </div>
        <div className="flex flex-col mt-12 w-full max-md:mt-10">
          <h3 className="text-3xl font-medium leading-none text-zinc-300">
            {title}
          </h3>
          <p className="pr-5 mt-3.5 w-full text-lg leading-7 text-white">
            {description}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ServiceCard;
