/**
 * This code was generated by Rushikesh
 */
import React from "react";
import ServiceCard from "./ServiceCard";
import background from "../../images/homepage_bg2.png"; 


const serviceData = [
  {
    title: "Inhouse Products",
    description:
      "State-of-the-art Products in Web3 domain like Algorithmic trading bots for price prediction and Crypto Portfolio Management Toolkit",
  },
  {
    title: "Blockchain Analytics Services",
    description:
      "We offer services in everything related to Data in web3. Our expertise includes but not limited to Designing and Auditing Smart Contracts, Blockchain Data Acquisition and AI Modelling, Blockchain Data Indexing solutions, Business Migration from Web2 to Web3",
  },
  {
    title: "AI Services",
    description:
      "We craft magic using AI... From insightful data analytics to development of complex AI-ML algorithms, and integrating GenAI to your business... we are the experts in this field.",
  },
  {
    title: "Corporate Trainings",
    description:
      "We offer Corporate Trainings for all roles throughout any organization to stay up-to-date with the ever evolving space of Web3 and AI",
  },
];

const ServiceSection = () => {
  return (
    <main 
    style ={{ backgroundImage: `url(${background})`, backgroundSize: "cover", backgroundPosition: "center center", backgroundRepeat: "no-repeat", opacity: 1}}
    className="flex flex-wrap gap-10 py-24 items-center pl-32 border-t border-b border-zinc-700 max-md:pl-5">
      <h2 className="grow shrink self-stretch w-[20%] my-auto text-6xl font-medium text-white leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]">
        We Help Businesses Grow by offering...
      </h2>
      <div className="flex flex-wrap w-[60%] grow shrink justify-center items-start self-stretch max-md:max-w-full">
        <div className="flex flex-wrap w-full max-md:max-w-full">
          {serviceData.slice(0, 2).map((service, index) => (
            <ServiceCard
              key={index}
              title={service.title}
              description={service.description}
            />
          ))}
        </div>
        <div className="flex flex-wrap w-[60%] grow shrink justify-center items-start self-stretch max-md:max-w-full">
          {serviceData.slice(2).map((service, index) => (
            <ServiceCard
              key={index + 2}
              title={service.title}
              description={service.description}
            />
          ))}
        </div>
      </div>
    </main>
  );
};
export default ServiceSection;
