/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col items-center w-full text-center text-white max-md:max-w-full"
    >
      <div
        data-layername="divCta"
        className="flex overflow-hidden justify-center items-center py-20 max-w-full w-full max-md:px-5"
      >
        <div
          data-layername="ResearchContainer"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch w-full basis-0 max-md:max-w-full"
        >
          <h1
            data-layername="ourResearchHeader"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            Our Research
          </h1>
          <p
            data-layername="Description"
            className="mt-16 text-2xl w-[85%] max-md:mt-10 max-md:max-w-full"
          >
            At Zenitheum, innovation meets knowledge. Dive into the world of
            Blockchain, Data Engineering, and AI with our transformative
            research. Our research team never gives up. Whatsoever may be the
            obstacle in any project, we conquer it and offer the research to the
            community. Stay updated with our latest advancements and discover
            how innovation is taking place at Zenitheum. If you are a keen
            researcher, join us on this odyssey and contribute to the endless
            possibilities of research. Happy reading and let's embark on this
            quest for knowledge together!
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
