/**
 * This code was generated by Rushikesh
 */
import React from "react";
import { useNavigate } from "react-router-dom";
import Research from "../../images/Research.png";

function OurContribution() {
  const navigate = useNavigate();

  const handleViewServices = () => {
    navigate("/research/researchpublications");
  };

  return (
    <section
      data-layername="TextImageContainer"
      className="flex items-center gap-10 px-20 py-20 w-full border-t border-b border-zinc-700 min-h-[913px] max-md:px-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="ContributionContainer"
        className="flex flex-col grow shrink justify-center w-[25%] text-white max-md:max-w-full"
      >
        <h2
          data-layername="ourContributionHeader"
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          Our Contribution...
        </h2>
        <p
          data-layername="Description"
          className="mt-10 text-2xl max-md:max-w-full"
        >
          We are enthusiastic about figuring out innovative solutions to the
          problems at hand. We have published some of the solutions with
          significant impact as research papers. This is our way of giving back
          to the community...
          <br />
        </p>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors duration-200"
          onClick={handleViewServices}
          aria-label=" View Our Research"
        >
          View Our Research
        </button>
      </div>
      <img
        loading="lazy"
        src={Research}
        alt="Our Contribution Illustration"
        className="object-cover grow shrink aspect-[1.47]  rounded-[100px] w-[45%] max-md:max-w-full"
      />
    </section>
  );
}

export default OurContribution;