/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import OurContribution from "./OurContribution";
import ResearchTeamHero from "./ResearchTeamHero";
import Footer from "./Footer";

function ResearchPage() {
  return (
    <div className="flex overflow-hidden flex-col pb-40 bg-zinc-900 max-md:pb-24">
      <Header />
      <OurContribution />
      <ResearchTeamHero />
      <Footer />
    </div>
  );
}

export default ResearchPage;
