/**
 * This code was generated by Builder.io
 */
import React from "react";
import NavTab from "./NavTab";

const navItems = [
  { label: "Home", isActive: true },
  { label: "Products", isActive: false },
  { label: "Services", isActive: false },
  { label: "Trainings", isActive: false },
  { label: "Our Clients", isActive: false },
  { label: "About Us", isActive: false },
  { label: "Research", isActive: false },
  { label: "Careers", isActive: false },
];

const Navbar = () => {
  return (
    <header className="flex flex-wrap w-full border-r border-neutral-600 max-md:mr-2 max-md:max-w-full">
      <nav className="flex flex-wrap items-start text-xl tracking-widest leading-none text-white uppercase whitespace-nowrap max-md:-mr-1 max-md:max-w-full">
        {navItems.map((item, index) => (
          <NavTab key={index} label={item.label} isActive={item.isActive} />
        ))}
      </nav>
      {/* <div className="flex overflow-hidden flex-col items-start px-16 border border-solid bg-zinc-900 border-neutral-700 min-h-[100px] max-md:px-5">
        <img
          loading="lazy"
          src="/Users/rushi/zenitheum/src/images/Zenitheum_bg_final.png"
          alt="Company logo"
          className="object-contain aspect-[1.04] w-[99px]"
        />
      </div> */}
    </header>
  );
};

export default Navbar;
