/**
 * This code was generated by Rushikesh
 */
import React from "react";
import TestimonialCard from "./TestimonialCard";
import GregImage from "../../../images/greg.png";
import DepImage from "../../../images/deepak.png";
import ShriImage from "../../../images/shrikant.png";
import logoImage from "../../../images/testiment_logo.png";

const testimonialData = [
  {
    logoSrc:logoImage,
    content:
      "Rushikesh worked with us to deliver our first Gemini Academy Training to 40+ Singaporean learners supporting us in content adaptation and training delivery. He was extremely collaborative, thoughtful, and proactive throughout the entire project. He demonstrated strong expertise in foundational AI knowledge in preparing the content, and did a great job in delivering the training in an engaging and confident manner. I would highly recommend Rushikesh to any organization, and would welcome working with him again on future projects.",
    name: "Gregory Satvinit",
    title: "M.D., TechHalo, Singapore",
    imageSrc:GregImage,
    imageAlt: "Gregory Satvinit",
    shadowColor: "rgba(93,93,255,1)",
  },
  {
    logoSrc:logoImage,
    content:
      "I would highly recommend the services offered by Zenitheum to the clients who seek expertise in the Web3 and Blockchain Domain. The team is highly skilled and innovative in their approach. Their dedication to the project and after-sell services are remarkable...",
    name: "Deepak Vasman",
    title: "Chief Business Officer, Density",
    imageSrc:DepImage,
    imageAlt: "Deepak Vasman",
    shadowColor: "rgba(93,93,255,1)",
  },
  {
    logoSrc:logoImage,
    content:
      "Zenitheum is an innovative leader in cutting edge Machine Learning and AI Technology. The team has innovated novel solutions for our business problems like addressing class imbalance in computer vision, implementing cyclical-learning-rate technique for computation cost optimization and saving training time. Their novel semi-supervised algorithm showcased 42x improved results over existing self-learning SSL algorithm. The product developments have led multiple peer reviewed journals like Springer. Zenitheum is an integral part of ChestAi's application development, and marketing. I strongly recommend Zenitheum for cost effective service with superior results.",
    name: "Shrikant Pawar",
    title: "Founder, ChestAi, USA.",
    imageSrc:ShriImage,
    imageAlt: "Shrikant Pawar",
    shadowColor: "rgba(93,93,255,1)",
  },
];

const TestimonialSection = () => {
  return (
    <section
      data-layername="testimonials"
      className="overflow-hidden bg-zinc-900 max-md:pr-5"
    >
      <div className="flex gap-10 py-20 px-20 max-md:flex-col">
        <div
          data-layername="column"
          className="flex flex-col w-[75%] max-md:ml-0 max-md:w-full"
        >
          <div className="flex flex-wrap grow gap-4 justify-center items-center h-[800px] rounded-[100px] shadow-2xl shadow-slate-500 border-y-gray-300 max-md:py-24 max-md:mt-10 max-md:max-w-full">
            <div className="grid grid-cols-3 gap-10 px-12 max-md:grid-cols-1 ">
              {testimonialData.map((testimonial, index) => (
                <TestimonialCard key={index} {...testimonial} />
              ))}
            </div>
          </div>
        </div>
        <aside
          data-layername="column"
          className="flex flex-col w-[25%] max-md:ml-0 max-md:w-full"
        >
          <div
            data-layername="TestimonialContainer"
            className="flex flex-col grow justify-center text-white max-md:mt-10"
          >
            <h2
              data-layername="TestimonialsHeader"
              className="text-6xl font-medium leading-[76px] max-md:text-4xl max-md:leading-[52px]"
            >
              Client Testimonials
            </h2>
            <p
              data-layername="Description"
              className="mt-12 text-2xl max-md:mt-10"
            >
              Client satisfaction is of utmost importance to us... We believe in
              building long term relationships with our clients through superior
              services and accountable After-Sell support.
            </p>
          </div>
        </aside>
      </div>
    </section>
  );
};

export default TestimonialSection;
