/**
 * This code was generated by Builder.io
 */
import React from "react";
import SocialLinks from "./SocialLinks";

function ContactForm() {
  return (
    <form className="flex overflow-hidden flex-col items-center p-16 max-w-full w-[916px] max-md:px-5">
      <div className="flex flex-col w-full text-2xl">
        <label htmlFor="name" className="text-white">
          Name
        </label>
        <input
          type="text"
          id="name"
          className="overflow-hidden px-5 py-4 mt-5 w-full border-2 border-solid border-zinc-700 text-zinc-700"
          placeholder="Jhon Doe"
        />
      </div>
      <div className="flex flex-col mt-10 w-full text-2xl whitespace-nowrap">
        <label htmlFor="email" className="text-white">
          Email
        </label>
        <input
          type="email"
          id="email"
          className="overflow-hidden px-5 py-4 mt-5 w-full border-2 border-solid border-zinc-700 text-zinc-700"
          placeholder="yourname@mail.com"
        />
      </div>
      <div className="flex flex-col mt-10 w-full text-2xl">
        <label htmlFor="subject" className="text-white">
          Subject
        </label>
        <input
          type="text"
          id="subject"
          className="overflow-hidden px-5 py-4 mt-5 w-full border-2 border-solid border-zinc-700 text-zinc-700"
          placeholder="I want to..."
        />
      </div>
      <div className="flex flex-col mt-10 w-full text-2xl whitespace-nowrap">
        <label htmlFor="message" className="text-white">
          Message
        </label>
        <textarea
          id="message"
          className="overflow-hidden px-8 pt-6 pb-60 mt-5 w-full border-2 border-solid border-zinc-700 text-zinc-700 max-md:px-5 max-md:pb-28"
          placeholder="Hello,...."
        ></textarea>
      </div>
      <div className="mt-10 text-2xl text-white">Contact us through</div>
      <SocialLinks />
    </form>
  );
}

export default ContactForm;
