/**
 * This code was generated by Builder.io
 */
import React from "react";
import InstaIcon from "../../images/instaicon.png";
import LinkedInIcon from "../../images/linkedinicon.png";
import TwitterIcon from "../../images/twittericon.png";
import FacebookIcon from "../../images/facebookicon.png";

const socialLinks = [
  {
    src: FacebookIcon,
    alt: "Facebook",
  },
  {
    src: TwitterIcon,
    alt: "Twitter",
  },
  {
    src: LinkedInIcon,
    alt: "LinkedIn",
  },
  {
    src: InstaIcon,
    alt: "Instagram",
  },
];

function SocialLinks({ className = "flex flex-wrap gap-6 items-start mt-10" }) {
  return (
    <div className={className}>
      {socialLinks.map((link, index) => (
        <div key={index} className="flex items-start w-6 max-w-[24px]">
          <div className="flex justify-center items-start w-6 max-w-[24px]">
            <div className="flex overflow-hidden items-start px-0.5 pt-0.5 pb-1 w-6">
              <img
                loading="lazy"
                src={link.src}
                alt={link.alt}
                className="object-contain w-5 aspect-square"
              />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export default SocialLinks;
