/**
 * This code was generated by Builder.io
 */
import React from "react";
import ContactSection from "./ContactSection";
import FooterLinks from "./FooterLinks";
import SocialLinks from "./SocialLinks";

const Footer = () => {
  return (
    <footer className="flex flex-col w-full max-md:max-w-full">
      <ContactSection />
      <FooterLinks />
      <div className="flex flex-wrap flex-1 gap-5 justify-center items-end px-28 mt-2.5 size-full max-md:px-5 max-md:max-w-full">
        <div className="flex flex-1 shrink items-end text-base text-white basis-0 min-w-[240px] max-md:max-w-full">
          <p className="min-w-[240px]">
            Copyright © 2024. All rights reserved by Zenitheum
          </p>
        </div>
        <SocialLinks />
      </div>
    </footer>
  );
};

export default Footer;
