/**
 * This code was generated by Builder.io
 */
import React from "react";

function Header() {
  return (
    <header
      data-layername="header"
      className="flex flex-col px-20 py-20 items-center w-full text-center text-white max-md:max-w-full"
    >
      <div
        data-layername="ExtraContainer"
        className="flex overflow-hidden justify-center w-full items-center max-md:px-5 max-md:py-24 max-md:max-w-full"
      >
        <div
          data-layername="ClientsContainer"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="ourClientsHeader"
            className="text-9xl font-medium leading-none max-md:max-w-full max-md:text-4xl"
          >
            Our Clients
          </h1>
          <p
            data-layername="Description"
            className="mt-16 text-2xl border border-black border-solid w-[75%] max-md:mt-10 max-md:max-w-full"
          >
            We are dedicated to fostering long-term relationships that empower
            our clients to achieve their goals in this rapidly evolving digital
            landscape. We have delivered satisfactory services to our clients
            all across the globe including, Singapore, USA, Italy and India.
          </p>
        </div>
      </div>
    </header>
  );
}

export default Header;
