/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header from "./Header";
import OurProjects from "./OurProjects";
import Footer from "./Footer";
import TestimonialSection from "./Testimonials/TestimonialSection";
import CollaborationSection from "./CollaborationSection";
function OurClients() {
  return (
    <div
      data-layername="ourClients"
      className="flex overflow-hidden flex-col pb-40 bg-zinc-900 max-md:pb-24"
    >
      <Header />
      <OurProjects />
      <TestimonialSection />
      <CollaborationSection />
      <Footer />
    </div>
  );
}

export default OurClients;
