/**
 * This code was generated by Builder.io
 */
import React from "react";
import DeliveryImage from "../../images/delivery.jpg";

function OurProjects() {
  return (
    <section
      data-layername="ourProjects"
      className="flex flex-wrap gap-10 items-center pr-12 mt-32 w-full text-white border-t border-b border-zinc-700 min-h-[990px] max-md:pr-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="divWNode99Feaec272B08085F1A2Bbf1C421530E9671Bbb9"
        className="flex flex-wrap grow shrink items-start self-stretch pl-14 my-auto min-h-[990px] min-w-[240px] w-[550px] max-md:max-w-full"
      >
        <div
          data-layername="frame6"
          className="flex grow shrink gap-10 items-center pr-16 pb-0.5 pl-16 border-t border-b border-zinc-700 min-h-[990px] min-w-[240px] w-[1476px] max-md:px-5"
        >
          <div
            data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
            className="flex flex-col justify-center self-stretch my-auto min-h-[988px] min-w-[240px] w-[588px]"
          >
            <h2
              data-layername="ourNoteworthyDeliveries"
              className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
            >
              Our Noteworthy Deliveries..
            </h2>
            <div
              data-layername="handsOnTrainingSessionAboutGoogleGeminisOptimalUsageTechniquesAndLimitationsOfGenAiModelsInCollaborationWithTechHaloSingaporeDevelopmentOfComputerVisionAlgorithmsForImageClassificationAndLocalizationOf18DiseasesFromChestXrayImagesInCollaborationWithChestAiUsaDevelopingImageGenAiAlgorithmsForCovid19ClassificationInCollaborationWithUnircItaly"
              className="mt-16 text-2xl max-md:mt-10 max-md:max-w-full"
            >
              Hands-on Training Session about Google Gemini's optimal usage
              techniques and limitations of GenAI models.
              <br />
              -In collaboration with: TechHalo, Singapore.
              <br />
              <br />
              Development of Computer Vision algorithms for Image classification
              and localization of 18 diseases from Chest-Xray Images
              <br />- In collaboration with: ChestAI, USA.
              <br />
              <br />
              Developing Image GenAI algorithms for COVID-19 classification
              <br />- In collaboration with: UNIRC, Italy.
              <br />
            </div>
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src={DeliveryImage}
        alt="Project showcase"
        className="object-contain grow shrink self-stretch my-auto aspect-[1.44] min-w-[240px] rounded-[100px] w-[943px] max-md:max-w-full"
      />
    </section>
  );
}

export default OurProjects;
