/**
 * This code was generated by Builder.io
 */
import React from "react";
import DeliveryImage from "../../images/delivery.jpg";

function OurProjects() {
  return (
    <section
      data-layername="ourProjects"
      className="flex gap-10 px-10 py-20 items-center w-full text-white border-t border-b border-zinc-700 max-md:pr-5 max-md:mt-10"
    >
      <div
        data-layername="ImageTextContainer"
        className="flex grow shrink gap-20 w-[65%] items-start"
      >
        <div
          data-layername="DeliveryContainer"
          className="flex flex-col justify-center"
        >
          <h2
            data-layername="DeliveriesHeading"
            className="text-6xl font-medium leading-[76px] max-md:text-4xl max-md:leading-[52px]"
          >
            Our Noteworthy Deliveries..
          </h2>
          <div
            data-layername="Description"
            className="mt-12 text-2xl max-md:mt-10"
          >
            1. Hands-on Training Session about Google Gemini's optimal usage
            techniques and limitations of GenAI models.
            <br />
            -In collaboration with: TechHalo, Singapore.
            <br />
            2. Development of Computer Vision algorithms for Image classification
            and localization of 18 diseases from Chest-Xray Images
            <br />- In collaboration with: ChestAI, USA.
            <br />
            3. Developing Image GenAI algorithms for COVID-19 classification
            <br />- In collaboration with: UNIRC, Italy.
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src={DeliveryImage}
        alt="Project showcase"
        className="object-cover grow shrink aspect-[1.04] rounded-[100px] w-[45%]"
      />
    </section>
  );
}

export default OurProjects;
