/**
 * This code was generated by Builder.io
 */
import React from "react";
import DeliveryImage from "../../images/delivery.jpg";

function OurProjects() {
  return (
    <section
      data-layername="ourProjects"
      className="flex flex-wrap px-20 py-20 items-center w-full text-white border-t border-b border-zinc-700 max-md:pr-5 max-md:mt-10 max-md:max-w-full"
    >
      <div
        data-layername="ImageTextContainer"
        className="flex flex-wrap grow shrink gap-20 w-[25%] items-start self-stretch max-md:max-w-full"
      >
        <div
          data-layername="DeliveryContainer"
          className="flex flex-col justify-center self-stretch"
        >
          <h2
            data-layername="DeliveriesHeading"
            className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
          >
            Our Noteworthy Deliveries..
          </h2>
          <div
            data-layername="Description"
            className="mt-16 text-2xl max-md:mt-10 max-md:max-w-full"
          >
            Hands-on Training Session about Google Gemini's optimal usage
            techniques and limitations of GenAI models.
            <br />
            -In collaboration with: TechHalo, Singapore.
            <br />
            <br />
            Development of Computer Vision algorithms for Image classification
            and localization of 18 diseases from Chest-Xray Images
            <br />- In collaboration with: ChestAI, USA.
            <br />
            <br />
            Developing Image GenAI algorithms for COVID-19 classification
            <br />- In collaboration with: UNIRC, Italy.
            <br />
          </div>
        </div>
      </div>
      <img
        loading="lazy"
        src={DeliveryImage}
        alt="Project showcase"
        className="object-cover grow shrink self-stretch aspect-[1.47] rounded-[100px] w-[35%] max-md:max-w-full"
      />
    </section>
  );
}

export default OurProjects;
