/**
 * This code was generated by Builder.io
 */
import React from "react";

function ServiceSection({
  title,
  description,
  buttonText,
  imageSrc,
  imageAlt,
  isReversed,
}) {
  const containerClasses = `flex flex-wrap gap-10 items-center pr-7 pl-20 max-w-full text-white border-t border-b border-zinc-700 w-[1920px] max-md:px-5 ${
    isReversed ? "flex-row-reverse" : ""
  }`;

  return (
    <section className={containerClasses}>
      <div
        data-layername="divWNode8F724A5176B938647BdeF393B3359C9D9671Bbb9"
        className="flex flex-col grow shrink justify-center self-stretch my-auto min-w-[240px] w-[389px] max-md:max-w-full"
      >
        <h2
          data-layername={title.toLowerCase().replace(/\s+/g, "")}
          className="text-6xl font-medium leading-[76px] max-md:max-w-full max-md:text-4xl max-md:leading-[52px]"
        >
          {title}
        </h2>
        <p className="mt-10 text-2xl max-md:max-w-full">{description}</p>
        <button
          data-layername="button"
          className="self-start py-4 pr-8 pl-8 mt-10 text-base uppercase bg-blue-700 rounded-[65px] max-md:px-5"
        >
          {buttonText}
        </button>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={imageAlt}
        className="object-contain grow shrink self-stretch my-auto aspect-[1.45] min-w-[240px] rounded-[101px] w-[1186px] max-md:max-w-full"
      />
    </section>
  );
}

export default ServiceSection;
