/**
 * This code was generated by Builder.io
 */
import React from "react";
import JDImage from "../../../images/JD.png";

function JobContent() {
  return (
    <section
      data-layername="jd"
      className="flex flex-col w-full text-white "
    >
      <div
        data-layername="JDBlock"
        className="flex overflow-hidden justify-center items-center py-20 px-20 w-full max-md:px-5 "
      >
        <div
          data-layername="JDContainer"
          className="flex overflow-hidden w-full flex-col flex-1 shrink justify-center items-center basis-0 "
        >
          <h1
            data-layername="JD Heading"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:text-4xl max-md:leading-[50px]"
          >
            Data Scientist
          </h1>
          <img
            loading="lazy"
            src={JDImage}
            alt="Job description illustration"
            className="object-cover mt-20  aspect-[1.69] w-[1014px] max-md:mt-10"
          />
          <div
            data-layername="JDContent"
            className="mt-20 text-2xl max-md:mt-10"
          >
            <h2 className="text-6xl font-bold leading-[52px]">
              Job Description: 
            </h2>
            <h3 className="text-4xl mt-8">(Internship, Duration: 2 months)</h3>
            <h3 className="text-4xl mt-8">Position Overview</h3>
            <li className="mt-4">
            Join Zentiheum, a forward-thinking startup at the intersection of AI and Web3, as a Data Scientist to play a critical role in developing our cutting-edge algorithmic trading bot.
            <br />
            You will work on designing and implementing advanced time series models to predict blockchain prices, backtest trading strategies, and validate models using sophisticated techniques such as Monte Carlo simulations and Walk-Forward Optimization.
            </li>
            <h3 className="text-4xl mt-8">Key Responsibilities:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Develop, fine-tune, and implement time series models for blockchain price prediction.</li>
              <li>Backtest and validate algorithmic trading strategies to optimize performance and minimize risk.</li>
              <li>Conduct Monte Carlo simulations and apply Walk-Forward Optimization to ensure robustness and adaptability of trading strategies.</li>
              <li>Collaborate with cross-functional teams to integrate insights and refine the bot’s predictive and execution capabilities</li>
              <li>Able to analyze complex data sets, identify patterns, and assess their potential business impact.</li>
            </ul>
            <h3 className="text-4xl mt-8">Skills Required:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Strong expertise in time series modeling, probability, and statistics.</li>
              <li>Proficiency in Python and data science libraries such as Pandas, NumPy, and scikit-learn; familiarity with blockchain data is a plus.</li>
              <li>Experience with financial markets, algorithmic trading, or trading bot development.</li>
              <li>Knowledge of backtesting frameworks and tools like PyAlgoTrade or similar libraries is advantageous.</li>
              <li>Prior experience in Web3, blockchain, or related fields is a plus. </li>
            </ul>
            <h3 className="text-4xl mt-8">What We Offer:</h3>
            <ul className="list-disc list-inside mt-4">
              <li>A chance to work on innovative projects at the forefront of AI and blockchain technology.</li>
              <li>Opportunities for professional growth, learning, and contributions to the Web3 revolution</li>
              <li>A dynamic, collaborative, and inclusive work environment that values your ideas and expertise.</li>
              <li>Certificate of internship and Experience Letter upon completion.</li>
            </ul>
            <h3 className="text-4xl mt-8">How to Apply</h3>
            <ul className="list-disc list-inside mt-4">
              <li>Submit your resume and cover letter to the email address: careers@zenitheum.com OR </li>
              <li>Submit the form on our website: https://zenitheum.com/contactus </li>
            </ul>
            <h3 className="text-4xl mt-8">Application Deadlines</h3>
            <ul className="list-disc list-inside mt-4">
              <li>28th Nov, 2024 </li>
            </ul>
            <br />
            <h3 className="text-4xl mt-8">Even if you do not meet all the requirements, feel free to get in touch with us. We believe in learning as we go. </h3>
            <h3 className="text-4xl mt-8">Join us at Zentiheum and be a part of the AI revolution!</h3>
          </div>
        </div>
      </div>
    </section>
  );
}

export default JobContent;
