/**
 * This code was generated by Builder.io
 */
import React from "react";

function StepCard({ number, title, description, isEven }) {
  return (
    <article
      className={`flex flex-col w-[calc(50%-10px)] max-md:w-full ${
        isEven ? "mt-32 max-md:mt-10" : ""
      }`}
    >
      <div
        className={`flex flex-col px-6 py-7 w-full rounded-lg border border-cyan-400 border-solid bg-white bg-opacity-10 max-md:px-5 ${
          isEven ? "max-md:mt-10" : ""
        } max-md:max-w-full`}
      >
        <div className="flex flex-col items-center min-h-[132px] max-md:max-w-full">
          <h2 className="self-start text-3xl font-semibold leading-none text-center text-white max-md:max-w-full">
            Step {number}: {title}
          </h2>
          <p className="mt-4 text-base font-medium leading-6 text-slate-300 max-md:max-w-full">
            {description}
          </p>
        </div>
      </div>
    </article>
  );
}

export default StepCard;
