/**
 * This code was generated by Builder.io
 */
import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";

function Layout({ children }) {
  return (
    <div
      data-layername="aiServices"
      className="flex overflow-hidden flex-col bg-zinc-900"
    >
      <Navbar />
      <main
        data-layername="main"
        className="flex flex-col w-full min-h-[4733px] max-md:max-w-full"
      >
        {children}
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
