/**
 * This code was generated by Builder.io
 */
import React from "react";

const footerLinks = [
  "Home",
  "Products",
  "Services",
  "Trainings",
  "Clients",
  "About Us",
  "Research",
  "Careers",
];

const FooterLink = ({ label }) => (
  <div className="gap-2.5 self-stretch whitespace-nowrap">{label}</div>
);

const ContactCard = ({ icon, title, content }) => (
  <div className="flex flex-col flex-1 shrink px-5 pt-5 pb-10 border-r basis-0 border-zinc-700 min-h-[304px] min-w-[240px] max-md:max-w-full">
    <div className="flex overflow-hidden justify-center items-center px-5 w-16 h-16 bg-neutral-800 rounded-[32px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain self-stretch my-auto w-7 aspect-square"
      />
    </div>
    <div className="flex flex-col mt-4 w-full">
      <h3 className="text-3xl font-medium leading-none text-zinc-300">
        {title}
      </h3>
      <div className="flex-1 shrink pr-5 mt-3.5 w-full text-lg leading-7 text-white whitespace-pre-line">
        {content}
      </div>
    </div>
  </div>
);

const SocialLink = ({ icon }) => (
  <a href="#" className="flex items-start w-6 max-w-[24px]">
    <div className="flex justify-center items-start w-6 max-w-[24px]">
      <div className="flex overflow-hidden items-start px-0.5 pt-0.5 pb-1 w-6">
        <img
          loading="lazy"
          src={icon}
          alt="Social media icon"
          className="object-contain w-5 aspect-square"
        />
      </div>
    </div>
  </a>
);

const Footer = () => {
  return (
    <footer className="flex overflow-hidden items-start pt-16 pb-7 w-full max-md:max-w-full">
      <div className="flex flex-col h-[427px] w-[1920px] max-md:max-w-full">
        <div className="flex flex-wrap self-center py-px w-full border-t border-b border-zinc-700 max-md:max-w-full">
          <div className="flex flex-col px-28 py-5 text-white border-r border-zinc-700 min-w-[240px] w-[649px] max-md:px-5 max-md:max-w-full">
            <div className="flex overflow-hidden gap-2.5 justify-center items-center self-start text-5xl whitespace-nowrap max-md:text-4xl">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/71deb2044f42ad1e40ace9ec8db65ee473e751f901ee4725876460c59b45fc7f?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                alt=""
                className="object-contain shrink-0 self-stretch my-auto aspect-[0.98] w-[86px]"
              />
              <div className="self-stretch my-auto max-md:text-4xl">
                Zenitheum
              </div>
            </div>
            <p className="mt-5 text-3xl font-medium tracking-widest">
              Zeniteum is a leading Blockchain Analytics and AI solutions firm,
              where we strive to empower businesses with tailored solutions that
              drive growth and efficiency.
            </p>
          </div>
          <nav className="flex flex-col flex-1 shrink self-start basis-[234px] min-w-[240px] max-md:max-w-full">
            <div className="flex flex-col justify-center px-12 py-6 w-full text-2xl leading-none text-white border-b border-zinc-700 max-md:px-5 max-md:max-w-full">
              <div className="flex flex-wrap gap-10 justify-between items-start w-full max-md:max-w-full">
                {footerLinks.map((link, index) => (
                  <FooterLink key={index} label={link} />
                ))}
              </div>
            </div>
            <div className="flex flex-wrap items-start w-full max-md:max-w-full">
              <ContactCard
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/755e65f35658c35f0bf56c0a583af86cb82869d550b926f2fe2656002afe4c59?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                title="Our Head Office"
                content="Prathamesh Park,\nBaner, Pune, 411045"
              />
              <ContactCard
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/9535b11c3777d69149267998b9cf7a30a208e8a76130ca32191b24b4ddb4d79b?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                title="Our Hotline"
                content="+91 7066497023"
              />
              <ContactCard
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/01af44e9b5ffe4c14d3d8528b031f94f302b9126f58513ad8de812402db7f4a2?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
                title="Mail Us"
                content="support@zenitheum.com\ncareers@zenitheum.com\nadmin@zenitheum.com\nrushikesh@zenitheum.com"
              />
            </div>
          </nav>
        </div>
        <div className="flex flex-wrap flex-1 gap-5 justify-center items-end px-28 mt-2.5 size-full max-md:px-5 max-md:max-w-full">
          <div className="flex flex-1 shrink items-end text-base text-white basis-0 min-w-[240px] max-md:max-w-full">
            <div className="min-w-[240px]">
              Copyright © 2024. All rights reserved by Zenitheum
            </div>
          </div>
          <div className="flex flex-wrap gap-6 items-start">
            <SocialLink icon="https://cdn.builder.io/api/v1/image/assets/TEMP/6f8347fa28e6c597a51142c106a5c91a112ca54bca0519a6156481fba08c0385?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22" />
            <SocialLink icon="https://cdn.builder.io/api/v1/image/assets/TEMP/9645fbe951416489c3946599f9a4880e5e04f844b6317c3a9d89b9becf558a41?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22" />
            <SocialLink icon="https://cdn.builder.io/api/v1/image/assets/TEMP/c3223b85f47c7bf2e68fecf03b55564b9a609e051329cf465ab3258847705a83?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22" />
            <SocialLink icon="https://cdn.builder.io/api/v1/image/assets/TEMP/0b92c1b5d24a4ac2cb2eaf6260a93a8a0fca4d8f0fdc0dbafd494f700b5efbf5?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22" />
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
