/**
 * This code was generated by Builder.io
 */
import React from "react";
import ResearchPaper from "./ResearchPaper";

function ResearchExperience() {
  const researchPapers = [
    { title: "OpenAI's GPT-3/ChatGPT: Suggests & Correct" },
    {
      title:
        "Addressing Class Imbalance Problem in Semantic Segmentation using Binary Focal Loss",
    },
    {
      title:
        "Cyclical Learning Rates (CLR'S) for Improving Training Accuracies and Lowering Computational Cost",
    },
    {
      title:
        "K-fold Semi-supervised Self-learning Technique for Image Disease Localization",
    },
    { title: "Neural Networks for Predicting Severity of Ovarian Carcinomas" },
    {
      title: "Single shot detector application for image disease localization",
    },
    {
      title:
        "Machine learning for identification and characterization of molecular gene signatures in progression of benign tumors",
    },
  ];

  return (
    <section
      data-layername="researchExperience"
      className="flex flex-col w-full text-white max-md:max-w-full"
    >
      <div
        data-layername="frame"
        className="flex overflow-hidden justify-center items-center px-28 pt-20 w-full min-h-[2912px] max-md:px-5 max-md:max-w-full"
      >
        <div
          data-layername="content"
          className="flex overflow-hidden flex-col flex-1 shrink justify-center items-center self-stretch my-auto w-full basis-0 min-h-[2750px] min-w-[240px] max-md:max-w-full"
        >
          <h1
            data-layername="ourResearchExperienceInAiMl"
            className="self-stretch text-9xl font-medium text-center leading-[144px] max-md:max-w-full max-md:text-4xl max-md:leading-[50px]"
          >
            Our Research Experience in AI-ML
          </h1>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2bde9abe964940500b55fb279f4c2ced75cd4df2b96598a96993b24135ecdc62?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
            alt="AI-ML Research Experience Illustration"
            className="object-contain mt-24 max-w-full aspect-[1.58] w-[1246px] max-md:mt-10"
          />
          {researchPapers.map((paper, index) => (
            <ResearchPaper key={index} title={paper.title} />
          ))}
        </div>
      </div>
    </section>
  );
}

export default ResearchExperience;
