/**
 * This code was generated by Builder.io
 */
import React from "react";

function Logo() {
  return (
    <div
      data-layername="logoFrame"
      className="flex overflow-hidden flex-col px-16 border border-solid bg-zinc-900 border-neutral-700 min-h-[100px] min-w-[240px] w-[245px] max-md:px-5"
    >
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/1c1eb17052800bf7be78ee46d52fbd3fd696e928834eda3f8990dd805c0e7ab4?placeholderIfAbsent=true&apiKey=6996dc1fa2444cff9994ea13907adb22"
        alt="Zenitheum logo"
        className="object-contain aspect-[1.04] w-[99px]"
      />
    </div>
  );
}

export default Logo;
