/**
 * This code was generated by Builder.io
 */
import React from "react";
import NavTab from "./NavTab";
import Logo from "./Logo";

const navItems = [
  { label: "Home", isActive: false },
  { label: "Products", isActive: false },
  { label: "services", isActive: true },
  { label: "trainings", isActive: false },
  { label: "our clients", isActive: false },
  { label: "about us", isActive: false },
  { label: "research", isActive: false },
  { label: "Careers", isActive: false },
];

function Navbar() {
  return (
    <nav
      data-layername="navbar"
      className="flex flex-wrap items-start w-full border-b border-zinc-700 min-h-[100px] max-md:max-w-full"
    >
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase whitespace-nowrap basis-[140px] min-w-[240px] max-md:max-w-full">
        {navItems.slice(0, 4).map((item, index) => (
          <NavTab key={index} label={item.label} isActive={item.isActive} />
        ))}
      </div>
      <Logo />
      <div className="flex flex-wrap flex-1 shrink items-start text-xl tracking-widest leading-none text-white uppercase basis-[140px] min-w-[240px] max-md:max-w-full">
        {navItems.slice(4).map((item, index) => (
          <NavTab key={index + 4} label={item.label} isActive={item.isActive} />
        ))}
      </div>
    </nav>
  );
}

export default Navbar;
